### ISSUE TITLE
fix (admin-ui): dashboard crash on clients page

### ISSUE THREAD

**Issue by jv18creator** [GluuFederation/flex#1002]
**Describe the bug**
1. UI crashes on clients page when searched for a client which is not available.
2. UI crashes after adding client and visit the client details in edit mode.

**To Reproduce**
Steps to reproduce the behavior for **1**:
1. Go to clients
2. Search for a client which does not exist in records
3. App will crash

Steps to reproduce the behavior for **2**:
1. Go to clients
2. Visit add client and create one
3. Save the client and try to visit the client
4. App will crash

**Comment by duttarnab** [comment]
Fixed
