### ISSUE TITLE
bug (admin-ui): two contradictory pop up 

### ISSUE THREAD

**Issue by mzico** [GluuFederation/flex#1004]
![Screenshot from 2023-05-10 14-10-47](https://github.com/GluuFederation/flex/assets/7156097/ca88d2aa-8d32-42e2-9064-2a4f97ff2bb8)

When I am going to "TEST" my SMTP configuration, two popups appearing. 
One saying... "Error processing request". Another saying "SMTP configuration successful".

**Comment by duttarnab** [comment]
I tested on https://flex-latest.gluu.info/admin. SMTP test is working properly for me.

![Clipboard - May 10, 2023 4_46 PM](https://github.com/GluuFederation/flex/assets/32794267/3f31db0b-d2b1-4d2d-ab07-9c1f2e95efab)

**Comment by mzico** [comment]
Try with some new installation. I entered SMTP configurations there in flex-latest.

**Comment by MohitMaliFtechiz** [comment]
@mzico , I checked this issue before. Actual reason behind this issue is explain in this issue   https://github.com/GluuFederation/flex/issues/996

**Comment by duttarnab** [comment]
fixed
