### ISSUE TITLE
Fix (admin-ui): Default acr for Admin UI is set to basic only 

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [GluuFederation/flex#1008]
**Describe the bug**
 Default acr for Admin UI is set to basic only.

**To Reproduce**
1. Install Flex
2. Go to admin UI 
3. Go to admin 
4. Go to script
5. enable any script (i.e otp )
6. go to auth-server->configuration-> properties
7. set default acr to desired authn script.
8. Get to the admin UI login page on private window
9. check the URl 

**Expected behavior**
acr_value in URL should be as it was set to default_acr value.

**Actual behavior**

acr_value is set to basic only.

**Screenshots**

**Desktop (please complete the following information):**
  - OS: rhel8
  - Browser chrome
  - Version  flex 1.0.13 nightly

**Comment by duttarnab** [comment]
In oxtrust there is a separate field to set the default acr for UI. We will need to introduce this field in Admin-UI to manage its authentication method

![image](https://github.com/GluuFederation/flex/assets/32794267/f5caf887-d176-439f-989f-0691496ee3e3)

**Comment by duttarnab** [comment]
> this SS is taken on different test client, there is no acr value set for the client. but on request url, it uses default acr set on auth-server, which is otp.

I think this is the expected behavior.

**Comment by MohitMaliFtechiz** [comment]
yes @duttarnab this is the  expected behavior but for admin UI this behavior is not same.

**Comment by duttarnab** [comment]
I have mentioned the reason here https://github.com/GluuFederation/flex/issues/1008#issuecomment-1543480178.

This should be coved under a new feature request (notbug).

**Comment by duttarnab** [comment]
We will reopen this issue if there is a requirement to set defaultAcr, especially for the Admin UI frontend.
