### ISSUE TITLE
feat: show alert in `Audit log` popup if count of the characters is less that required count

### ISSUE THREAD

**Issue by duttarnab** [GluuFederation/flex#101]
The audit log popup requires text with at least 10 characters for submission. 
We need to show an alert if the characters count is < 10.

Something like `<character_count> more characters required.`

![image](https://user-images.githubusercontent.com/32794267/155851271-d725a0e3-f8ca-4650-980e-a863a22a393c.png)

**Comment by duttarnab** [comment]
done

**Comment by mjatin-dev** [comment]
checked on https://admin-ui-test.gluu.org/ working fine, so closing this issue.
