### ISSUE TITLE
fix(flex): getting file not found error while installing flex

### ISSUE THREAD

**Issue by manojs1978** [GluuFederation/flex#1028]
**Describe the bug**
getting file not found error while installing flex
FileNotFoundError: [Errno 2] No such file or directory: '/opt/dist/jans/gluu-casa/casa.war'

**To Reproduce**
1. donwload package flex-5.0.0-13-suse15.x86_64.rpm
2. install rpm
3. run setup script 
4. python3 /opt/jans/jans-setup/flex/flex-linux-setup/flex_setup.py -admin-ui-ssa [filename]
5. See error

**Expected behavior**
should not get any error

**Screenshots**
![image](https://github.com/GluuFederation/flex/assets/5729240/75904adb-9198-4b7d-9143-ed8457355e8c)

**Desktop (please complete the following information):**
  - OS: ubnntu /suse
  - Version ubuntu 22 / suse 15 / rhel
  - DB mysql
  - flex 5.0.0-13

**Smartphone (please complete the following information):**
  - Device:ubunut/suse

**Additional context**

**Comment by devrimyatar** [comment]
@moabu  Casa files were not downloaded while packaging:

![image](https://github.com/GluuFederation/flex/assets/6398752/2f68388e-3456-4bd5-acc9-86373b1da36b)

**Comment by devrimyatar** [comment]
Latest build is good
