### ISSUE TITLE
fix(flex): while installig flex, getting decode error when entered ssa file path 

### ISSUE THREAD

**Issue by manojs1978** [GluuFederation/flex#1032]
**Describe the bug**
while installig flex, getting decode error when entered ssa file path but it is working when paste same ssa 

**To Reproduce**
1. install flex 5.0.0.14 nightly  build
2. save ssa in file and enter file path (for ex. /root/ssa.txt) when prompted for file path.

**Expected behavior**
should not get error when entered ssa file path 

**Screenshots**
![image](https://github.com/GluuFederation/flex/assets/5729240/6f67e4f4-3dd7-46e6-8cd4-072b6243baa8)

**Desktop (please complete the following information):**
  - OS: suse 15
  - Version 15
  - -DB mysql
  - flex 5.0.14. nightly

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
Can't replicate on Ubuntu 20:
![image](https://github.com/GluuFederation/flex/assets/6398752/15728774-613a-49e9-afd6-808e8bd9c991)
