### ISSUE TITLE
chore(admin-ui): misc adjustments in Agama screens

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/flex#1035]
Browsing to Auth server > Agama

1. When clicking on the plus icon, it shows

![Screenshot from 2023-05-24 07-01-53](https://github.com/GluuFederation/flex/assets/5444180/8ec1bcba-c69d-4f9b-a755-bb9648f80e95)

- Please change the dialog title to "Add Agama project"
- Please change "Drag 'n' drop" to simply "Drag"

2. After the gama and shasum files are selected, the table is populated. Hovering on the information icon shows

![Screenshot from 2023-05-24 07-04-19](https://github.com/GluuFederation/flex/assets/5444180/0bb0578d-60bf-4832-a274-f7f441ad0ed6)

- I guess what you really meant was "See project details"
- If possible, change the "Manage configuration"  icon for a settings wheel icon or similar. The pencil conveys the idea a project can be edited. Edition of projects does not really exist - just full replacement uploading a gama file again
- To keep it aligned with TUI, change "ERROR" column label to "ERRORS"

**Comment by duttarnab** [comment]
Done
