### ISSUE TITLE
feat(admin-ui): check or warn if Agama engine is enabled before project uploading

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/flex#1036]
I would be good not to allow deployment of Agama projects if Agama is disabled, or at least warn the user that Agama should be enabled for projects to be effectively deployed.

I'm refering to the config found in Auth server > Configuration > Properties > agama configuration section > enabled switch

I think TUI Is doing something similar, you may like to check

Otherwise users will see a screen like this forever:

![Screenshot from 2023-05-24 07-11-42](https://github.com/GluuFederation/flex/assets/5444180/0357e93d-f3b5-4799-af75-3129b788bcc1)

**Comment by duttarnab** [comment]
Done
