### ISSUE TITLE
fix(flex):  casa war not found error while installing flex

### ISSUE THREAD

**Issue by manojs1978** [GluuFederation/flex#1058]
**Describe the bug**
 casa war not found error while installing flex

**To Reproduce**
1. download 5.0.0.14 nightly build package
2. install flex rpm
3. run flex_setup,py 

**Expected behavior**
should not get any error

**Screenshots**
![image](https://github.com/GluuFederation/flex/assets/5729240/519d079c-8b2f-47ed-8b9b-1cfc2098eaf9)

**Desktop (please complete the following information):**
  - OS: ubuntu
  - Version  22
  - DB opendj
  - Flex 5.0.0-14 nightly build

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jgomer2001** [comment]
I found suspicious that you are trying an RPM file in ubuntu ...

**Comment by jgomer2001** [comment]
Reopen if you face this again and ping me
