### ISSUE TITLE
fix(casa): getting signature error when launching casa

### ISSUE THREAD

**Issue by manojs1978** [GluuFederation/flex#1061]
**Describe the bug**

**To Reproduce**
1. install flex
2. launch casa
3. 4. See error

**Expected behavior**
should not get any error

**Screenshots**
![image](https://github.com/GluuFederation/flex/assets/5729240/118698a4-db42-45f3-9a5e-51d95d167a96)

**Desktop (please complete the following information):**
  - OS: ubuntu22
  - Version 22
  - flex 5.0.0-14.nightly
  - DB pgsql / mysql

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jgomer2001** [comment]
Unable to reproduce as of now
