### ISSUE TITLE
docs: Import Casa and Super Gluu documentation into Flex

### ISSUE THREAD

**Issue by ossdhaval** [GluuFederation/flex#1062]
As per @nynymike's comment in chat  Gluu Casa and Super Gluu documentation should be moved to Flex. This involves

- [ ] Move Casa documentation from [here](https://gluu.org/docs/#gluu-casa)
- [ ] Move Super Gluu documentation from [here](https://gluu.org/docs/#super-gluu)
- [ ] Remove Casa section from [here](https://docs.gluu.org/head/admin/casa/)

Casa and Super Gluu should be two new top level documentation categories as shown in the image below:

![Clipboard - May 29, 2023 11_31 AM](https://github.com/GluuFederation/flex/assets/343411/3573a4bb-c5ab-4614-a050-c1c5348034e9)

**Comment by ossdhaval** [comment]
@moabu Can you just double check the source and destinations that I have listed above? I am new to Flex and Gluu docs structure.

**Comment by ossdhaval** [comment]
@moabu 

For Casa and Super Gluu, which branch has the latest docs? Both have a 4.5 branch, is that the `head`? [Out here](https://gluu.org/docs/#gluu-casa) it shows latest version for Casa as 4.4 and Super Gluu as 3.1.3.

If you go by the branch to receive most recent commit, then it is 4.5 for Casa and 3.1.3 for Super Gluu.

**Comment by moabu** [comment]
Yes its correct. The documentation was before following breaking the documentation into repositories. But you are to take the documentation from `4.5` and `.3.1.3` respectively . A lot will change due to the fact that super gluu is now in a private repo.
