### ISSUE TITLE
fix(casa): fido2 enrollment not working

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/flex#1077]
> For USB tokens or my Macbook
> I think there have been some major changes in Chrome

![Clipboard - June 8, 2023 12_35 PM](https://github.com/GluuFederation/flex/assets/5444180/a9441b96-1b66-4fc6-a53a-04c120cc24f0)

**Comment by maduvena** [comment]
![image](https://github.com/GluuFederation/flex/assets/12072533/e7d5caca-b0b6-43eb-83d8-9c07473cf0eb)

**Comment by Milton-Ch** [comment]
@jgomer2001 

Can you test on this server https://milton-ch-normal-crab.gluu.info/casa/
I have created a login for you:

```
Username: jose1
Password: jose1
```

**Comment by Milton-Ch** [comment]
> ![image](https://user-images.githubusercontent.com/12072533/244597531-e7d5caca-b0b6-43eb-83d8-9c07473cf0eb.png)

This error occurred because they did not configure SSL on the server, I spoke to @mzico and he confirmed that this was the case.

**Comment by nynymike** [comment]
THANK YOU!!!
