### ISSUE TITLE
Admin UI: Errors in the logging configuration screen

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/flex#108]
`WARN` level is missing. And there is a typo: JSK instead of JDK

see image:
![Screenshot from 2022-03-01 09-42-12](https://user-images.githubusercontent.com/5444180/156191858-b1ed167c-0eb9-4dcf-94d9-7119690c7f03.png)

**Comment by mjatin-dev** [comment]
Fixed : https://github.com/GluuFederation/flex/pull/109

**Comment by mjatin-dev** [comment]
Fixed and checked on live, so closing this issue.
