### ISSUE TITLE
fix(admin-ui): unable to load adminui randomly

### ISSUE THREAD

**Issue by manojs1978** [GluuFederation/flex#1098]
**Describe the bug**
unable to load adminui randomly

**To Reproduce**
1. install flex 5.0.15.nightly
2. launch adminui
3. wait to load admin page

**Expected behavior**
should not get any error  to launch admin

**Screenshots**
![image](https://github.com/GluuFederation/flex/assets/5729240/a169bb44-13b1-407b-8f85-e9afa5c7c2b0)

**Desktop (please complete the following information):**
  - OS: suse 15
  - Version 
  - DB- pgsql
  - flex 5.0.15.nighlty

**Smartphone (please complete the following information):**

**Additional context**
[adminui.log](https://github.com/GluuFederation/flex/files/11743305/adminui.log)

**Comment by duttarnab** [comment]
This is fixed. That's why in issue `https://github.com/GluuFederation/flex/issues/1110` user was able to reach license activation page.
