### ISSUE TITLE
fix(admin-ui),unable to start free trial 

### ISSUE THREAD

**Issue by manojs1978** [GluuFederation/flex#1106]
**Describe the bug**
unable to start free trial 

**To Reproduce**
1. install flex 5.0.0.-15 nighlty 
2. launch admin
3. click free trial
4. 

**Expected behavior**

should able to start free trial and proceed to admin dashboard.
**Screenshots**
![image](https://github.com/GluuFederation/flex/assets/5729240/6ec951aa-cd5d-4d9c-8408-2b34fc6eaa08)

**Desktop (please complete the following information):**
  - OS: suse
  - Version 15
  - -DB mysql
  - fflex 5.0.0.-15. nighlty

**Smartphone (please complete the following information):**

**Additional context**

**Comment by duttarnab** [comment]
fixed
