### ISSUE TITLE
fix(casa): metadata for authenticator missing

### ISSUE THREAD

**Issue by SafinWasi** [GluuFederation/flex#1109]
When registering a Yubikey 5 NFC via Casa, registration fails with the following log:

```
/fido2.log
16-06 14:37:44.837 INFO  [qtp1287934450-15] [org.gluu.fido2.service.mds.AttestationCertificateService] (AttestationCertificateService.java:117) - No metadata for authenticator c1f9a0bc1dd2404ab27f8e29047a43fd. Attempting to contact MDS
16-06 14:37:44.842 WARN  [qtp1287934450-15] [org.gluu.fido2.service.mds.AttestationCertificateService] (AttestationCertificateService.java:123) - Failed to get metadata from Fido2 meta-data server
16-06 14:41:07.679 INFO  [qtp1287934450-20] [org.gluu.fido2.service.mds.AttestationCertificateService] (AttestationCertificateService.java:117) - No metadata for authenticator c1f9a0bc1dd2404ab27f8e29047a43fd. Attempting to contact MDS
16-06 14:41:07.679 WARN  [qtp1287934450-20] [org.gluu.fido2.service.mds.AttestationCertificateService] (AttestationCertificateService.java:123) - Failed to get metadata from Fido2 meta-data server
```

**Desktop (please complete the following information):**
  - OS: Arch Linux x64 kernel 6.3.7
  - Browser: Chromium 114.0.5735.106, Firefox 114.0.5735.106

**Comment by jgomer2001** [comment]
A side comment: my [Yubikey 5C](https://www.yubico.com/co/product/yubikey-5-series/yubikey-5c/) enrolls ok

**Comment by SafinWasi** [comment]
Upon investigation, we found that using a self signed certificate causes the TOC file to be incorrectly updated, which leads to devices being unrecognized. This can be worked around by manually downloading the TOC file from https://mds3.fidoalliance.org/. This is applicable to both Gluu and Jans.

**Comment by Milton-Ch** [comment]
The root problem, I think, was that the @SafinWasi environment did not download the `toc.jwt` file correctly during installation.
This file contains all the Metadata Services, which are used to perform the validation of the devices during atestation.

**Comment by nynymike** [comment]
Does the `toc.jwt` file get downloaded in `setup.py`or it is a manual step? Where is this documented?

**Comment by maduvena** [comment]
It is documented here https://github.com/JanssenProject/jans/blob/main/docs/admin/fido/vendor-metadata.md @nynymike
