### ISSUE TITLE
fix(admin-ui): unable to add openid scope while creating AS client

### ISSUE THREAD

**Issue by manojs1978** [GluuFederation/flex#1115]
**Describe the bug**
unable to add openid scope while creating AS client

**To Reproduce**
1. install flex 5.0.0-15.nightly 
2. launch admin
3. cerate client and try to add openid scope

**Expected behavior**
should have openid in dropdown to select
**Screenshots**
![image](https://github.com/GluuFederation/flex/assets/5729240/156cdfe5-1c0d-4e8f-9046-0a75b1f80135)

**Desktop (please complete the following information):**
  - OS: suse 15
  - Version sp4
  - flex 5.0.0-15.nightly
  - DB mysql

**Smartphone (please complete the following information):**

**Additional context**

**Comment by duttarnab** [comment]
fixed
