### ISSUE TITLE
chore(flex-linux-setup): remove duo script from flex

### ISSUE THREAD

**Issue by duttarnab** [GluuFederation/flex#1120]
As per the following instruction, we need to remove the duo script from Flex installation.

https://github.com/GluuFederation/flex/issues/1108#issuecomment-1597269021

**Comment by iromli** [comment]
@duttarnab In CN version, this deletion won't be included in docker-admin-ui. Instead it will be applied in upstream docker-jans-persistence-loader (with custom ENV flag).

**Comment by iromli** [comment]
Waiting for https://github.com/JanssenProject/jans/pull/5370 (deletion support) being merged.

**Comment by ossdhaval** [comment]
@duttarnab @iromli This will have impact on documentation. Please search for relevant terms in Jans and Flex docs and update as appropriate as part of this PR itself. This will help in moving code and docs in lock steps.

**Comment by duttarnab** [comment]
done
