### ISSUE TITLE
fix(linux-setup) : pre requisites are not installing while installing flex package

### ISSUE THREAD

**Issue by manojs1978** [GluuFederation/flex#1132]
**Describe the bug**
pre requisites are not installing while installing flex package

**To Reproduce**
1. download flex 5.0.0.15.nightly
2. sudo yum install flex-5.0.0-15.nightly-suse15.x86_64.rpm
3. See error

**Expected behavior**
all pre requisites required for flex package should install with installer
**Screenshots**
![image](https://github.com/GluuFederation/flex/assets/5729240/be48e907-36b9-42ec-8d53-b6d08cf148bd)

**Desktop (please complete the following information):**
  - OS: RHEL8
  -   - Browser [e.g. chrome, safari]
  - Version 8
  - DB any
  - flex 5.0.0.15.nightly

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
@manojs1978 This is not an issue, you don't have registered repos that provides those packages. I guess installing epel-release repository will solve this issue.

**Comment by manojs1978** [comment]
sudo SUSEConnect -p PackageHub/15.4/x86_64

command helped to resolve repo issues
