### ISSUE TITLE
fix(linux-setup): unable to uninstall flex

### ISSUE THREAD

**Issue by manojs1978** [GluuFederation/flex#1146]
**Describe the bug**
 unable to uninstall flex, getting error "cannot create directory"

**To Reproduce**
1. install flex 5.0.0-15.nightly
2. uninstall flex "sudo python3 /opt/jans/jans-setup/flex/flex-linux-setup/flex_setup.py --remove-flex"
3. sudo python3 /opt/jans/jans-setup/install.py -uninstall
4. sudo zypper remove flex
5. Scroll down to '....'
6. See error

**Expected behavior**

**Screenshots**
![image](https://github.com/GluuFederation/flex/assets/5729240/8bab91c5-5c71-40d8-9e6d-ea58a86ebe74)

**Desktop (please complete the following information):**
  - OS: suse
  - Version 15sp4
  - DB mysql
  - flex 5.0.0-15.nightly

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
@manojs1978 Right commands are:

```
python3 /opt/jans/jans-setup/flex/flex-linux-setup/flex_setup.py --remove-flex
python3 /opt/jans/jans-setup/install.py -uninstall -yes --keep-downloads --keep-setup
zypper remove flex
```
