### ISSUE TITLE
fix(admin-ui): showing  lic page again

### ISSUE THREAD

**Issue by manojs1978** [GluuFederation/flex#1147]
**Describe the bug**
showing  lic page again

**To Reproduce**
1. install flex 5.0.0-15.nightly
2. launch admin and start free trial
3. close browser and login again in browser

**Expected behavior**
once we start 30 days free trial it should continue , no need to start free trial again or should not get lic page till 30 days

**Screenshots**
![image](https://github.com/GluuFederation/flex/assets/5729240/f8f44b58-1bd7-4cab-b688-81e2da1cad4d)

**Desktop (please complete the following information):**
  - OS: suse 15 sp 4
  - Version 15 sp 4
  - DB mysql
  - flex 5.0.0.-15.nightly

**Smartphone (please complete the following information):**

**Additional context**

**Comment by manojs1978** [comment]
https://github.com/GluuFederation/flex/assets/5729240/bb24d990-e137-4cb4-a5bf-a0b94d23c9a1

**Comment by duttarnab** [comment]
I have noticed that often backend apis (mostly /license) take a longer time to respond to the request made by frontend. This is not happening every time. 

Frontend cancels the request if it takes more than 50000ms.

I am trying to reproduce this issue.

**Comment by duttarnab** [comment]
![image](https://github.com/GluuFederation/flex/assets/32794267/eab13647-365a-47c9-99ae-e3d495f551dd)

as per the last discussion, this issue is now resolved. Closing the issue.
