### ISSUE TITLE
fix(jans-config-api): config api service is going down after VM restart

### ISSUE THREAD

**Issue by manojs1978** [GluuFederation/flex#1156]
**Describe the bug**
config api service is going down after restart

**To Reproduce**
1. install flex5.0.0.-15.nightly
2. restart vm
3.. cehck all services sudo systemctl list-units --all "jans*"

**Expected behavior**
all services should be up
**Screenshots**
![image](https://github.com/GluuFederation/flex/assets/5729240/24c51394-5f2e-450d-8c54-e46d03253e33)

**Desktop (please complete the following information):**
  - OS: rhel8
  - Browser 
  - Version 8
  - DB mysql
  - flex 5.0.5-15.nighlty

**Smartphone (please complete the following information):**

**Additional context**

**Comment by pujavs** [comment]
It seems that the services on this env are taking time to start, it's not only jans-config-api but sometimes others services as well. Have you tested this scenario (reboot and chk service status) earlier ? Is this happening only for RHEL 8 VM?

![image](https://github.com/GluuFederation/flex/assets/43700552/79ef52f2-4781-4f16-80f3-478f4e5395e5)


https://github.com/GluuFederation/flex/assets/43700552/f2ca3b8d-3c09-448c-8392-313d8e7465a6
There does not seem to be problem specific to config-api, I will see if the startup time of config-api has increased or can be improved.

**Comment by pujavs** [comment]
@manojs1978, are you still facing this issue with config-api?

**Comment by manojs1978** [comment]
no , looks good now
