### ISSUE TITLE
fix(admin-ui): unable to save smtp configuration

### ISSUE THREAD

**Issue by manojs1978** [GluuFederation/flex#1168]
**Describe the bug**

**To Reproduce**
1. install flex 5.0.0.15.nightly
2. launch admin
3. add smtp configuration and save it

**Expected behavior**
should able to save and test smtp configuration.

**Screenshots**
![image](https://github.com/GluuFederation/flex/assets/5729240/c7c55261-b4cd-4ce3-b1d3-0285be93d124)

**Desktop (please complete the following information):**
  - OS: ubuntu22
  - Version 
  - DB mysql/pgsql
  - flex 5.0.0.15.nightly

**Smartphone (please complete the following information):**

**Additional context**

**Comment by duttarnab** [comment]
Trying to reproduce the issue.
