### ISSUE TITLE
Fix (admin-ui ): Cache refresh should not be activated by default .

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [GluuFederation/flex#1178]
**Describe the bug**
Cache refresh should not be activated by default .

**To Reproduce**
1. install flex 5.0.0.15-nightly 
2. launch admin UI
4. go to cache refresh and check cache refresh active status 

**Expected behavior**
cache refresh should not be enabled by default

**Screenshots**
![Screenshot from 2023-07-05 18-58-10](https://github.com/GluuFederation/flex/assets/34593983/d9987fde-a861-4279-85ef-a5dc2bbae828)

**Desktop (please complete the following information):**
  - OS: rhel8 / ubuntu20
  - Version 22
  - DB- mysql/opendj
  - flex 5.0.0.15-nighlty

**Comment by duttarnab** [comment]
Hi @shekhar16 please close this issue once it is resolved.

**Comment by duttarnab** [comment]
fixed
