### ISSUE TITLE
feat: the `X` is a confusing on top

### ISSUE THREAD

**Issue by duttarnab** [GluuFederation/flex#118]
For example, when I edit a script… and let’s say I want to cancel out. I see this:
And then you hit the x… and the navigation disappears ..

![image](https://user-images.githubusercontent.com/32794267/156406098-a7db4c2b-ecec-4d04-b135-734a5e5c7bea.png)

**Comment by mjatin-dev** [comment]
Fixed and check the fix on https://admin-ui-test.gluu.org/
