### ISSUE TITLE
fix(admin-ui): smtp configuration test is failing

### ISSUE THREAD

**Issue by manojs1978** [GluuFederation/flex#1209]
**Describe the bug**
smtp configuration test is failing

**To Reproduce**
1. install flex 5.0.0-15.nightly
2. add smtp configuration 
3. save it and test

**Expected behavior**
test should be sucessful
**Screenshots**
![image](https://github.com/GluuFederation/flex/assets/5729240/73a48028-4e07-4d59-8cfc-8253fcc2eb3e)

**Desktop (please complete the following information):**
  - OS: suse
  - Version 15
  - flex 5.0.0-15.nightly
  - DB mysql

**Smartphone (please complete the following information):**

**Additional context**

**Comment by duttarnab** [comment]
fixed
