### ISSUE TITLE
fix (flex-linux-setup): in jans-config-api.xml the plugin jar paths should be comma separated

### ISSUE THREAD

**Issue by duttarnab** [GluuFederation/flex#124]
In `/opt/jans/jetty/jans-config-api/webapps/jans-config-api.xml` jetty configuration file the plugins are mentioned in separate `<Set name="extraClasspath">` tags. Due to this, all plugins apis are not added to config-api.

To fix this we need to mention them in the same tag with comma-separated paths.

**Current**
```
<Set name="extraClasspath">/opt/jans/jetty/jans-config-api/custom/libs/admin-ui-plugin-distribution.jar</Set><Set name="extraClasspath">/opt/jans/jetty/jans-config-api/custom/libs/scim-plugin.jar</Set>
```

**Expected**
```
<Set name="extraClasspath">/opt/jans/jetty/jans-config-api/custom/libs/admin-ui-plugin-distribution.jar,/opt/jans/jetty/jans-config-api/custom/libs/scim-plugin.jar</Set>
```

**Comment by mbaser** [comment]
Fixed by commit https://github.com/JanssenProject/jans/commit/bfb0bfe63abdc86a1384badfe15e3d985213001e
