### ISSUE TITLE
fix(jans-link):  test ldap connection is failing

### ISSUE THREAD

**Issue by manojs1978** [GluuFederation/flex#1260]
**Describe the bug**
test ldap connection is failing

**To Reproduce**
1. isntall flex 5.0.0.-16.nightly
2. add ldap server details in jans-link
3. save and test ldap connection

**Expected behavior**
test should be successful

**Screenshots**
![image](https://github.com/GluuFederation/flex/assets/5729240/f47cc486-59f6-43a2-afe7-ed81349ec565)

**Desktop (please complete the following information):**
  - OS: suse
  - Version 15
-Flex 5.0.0.-16.nghtly
-DB mysql

**Smartphone (please complete the following information):**

**Additional context**

**Comment by duttarnab** [comment]
Remove the `Test` LDAP configuration button from `Source Backend LDAP Servers` tabs. It will be restored after https://github.com/JanssenProject/jans/issues/5818 is addressed.
