### ISSUE TITLE
fix(jans-link): not able to configure server ip address in jans-link

### ISSUE THREAD

**Issue by manojs1978** [GluuFederation/flex#1261]
Describe the bug
Not able to configure server ip address in jans-link configuration.

To Reproduce

install jans-server
run jans-cli-tui.
go to jans-link
set all configuration
check server ip address in configuration after some time
Expected behavior
server ip address value should be changed to provided ip address.

Actual behavior
server ip address value stays 225.225.225.225
**Screenshots**
![image](https://github.com/GluuFederation/flex/assets/5729240/e5802826-0f3c-4949-95be-5a01898f5f01)

**Desktop (please complete the following information):**
  - OS: suse
  - Version 15 sp4
  - DB mysql
  - flex 5.0.0-16.nightly

**Smartphone (please complete the following information):**

**Additional context**

**Comment by duttarnab** [comment]
Removed `Server IP Address` from jans-link `Configuration` tab of GUI.
![image](https://github.com/GluuFederation/flex/assets/32794267/a30979f1-878b-4082-a504-707cc7d0c626)
