### ISSUE TITLE
feat(flex-linux-setup): adding separate token client to facilitate authentication using js library

### ISSUE THREAD

**Issue by duttarnab** [GluuFederation/flex#1309]
**Parent ticket#** https://github.com/GluuFederation/flex/issues/1303

1.  Set 'jansTknEndpointAuthMethod' to `none` to Admin UI (auth) client (generated by setup script).
2.  Generate a new `Admin UI Token Client` with the following properties

- 'jansAccessTknAsJwt'` --- `true`
- `jansAccessTknSigAlg` --- `RS256`
- `jansAppTyp` --- `web`
- `jansAttrs.runIntrospectionScriptBeforeJwtCreation` --- `true`
- `jansAttrs.introspectionScripts` --- `["inum=A44E-4F3D,ou=scripts,o=jans"]`
- `jansGrantTyp` --- `client_credentials`
- `jansIdTknSignedRespAlg` --- `RS256`
- `jansPersistClntAuthzs` --- `true`
- `jansTknEndpointAuthMethod` --- `client_secret_basic`

3. Add `Admin UI Token Client` client_id and client_secret to admin-ui token client configuration.

```
tokenServerClient.clientId
tokenServerClient.clientSecret
```
![image](https://github.com/GluuFederation/flex/assets/32794267/3f24a5cd-caec-48af-9bc8-21c351260548)

**Comment by duttarnab** [comment]
Hi @iromli 

We need a separate token client as Admin UI is using a typescript lib to manage auth code flow during login. It uses PKCE and thus need `jansTknEndpointAuthMethod`=`node` (to avoid using client_secret on UI).

**Comment by iromli** [comment]
@duttarnab noted, work is in progress.
