### ISSUE TITLE
chore(admin-ui): code optimization and refactoring

### ISSUE THREAD

**Issue by duttarnab** [GluuFederation/flex#1313]
- Remove the async code wherever not required
- Add the missing tooltips in the code
- Explore how code splitting can be implemented and its benefits
- Review if correct React-redux coding practices are followed in each module.

**Comment by jv18creator** [comment]
for react-redux code practices, we will remove the `connect` api from react-redux & will replace its usage with `useSelector` & `useDispatch` hooks. This Hooks API are recommended by the [offical react-redux docs.](https://redux.js.org/style-guide/#use-the-react-redux-hooks-api)
