### ISSUE TITLE
fix(jans-link): NullPointerException in jans-link

### ISSUE THREAD

**Issue by manojs1978** [GluuFederation/flex#1353]
**Describe the bug**
NullPointerException in jans-link cache refresh

**To Reproduce**
1. install flex 5.0.19.nightly
2. configure jans-link and AD server
3. See error in log

**Expected behavior**
users data should be synced

**Screenshots**
![image](https://github.com/GluuFederation/flex/assets/5729240/d92471dd-b2f9-4140-a795-ab122141705a)
![image](https://github.com/GluuFederation/flex/assets/5729240/9985ffae-66ad-4ad9-ba4c-f369bc9425ae)

**Desktop (please complete the following information):**
  - OS: rhel
  - Version 8
  - flex 5.0.19.nightly
  - DB mysql

**Smartphone (please complete the following information):**

**Additional context**
[log.zip](https://github.com/GluuFederation/flex/files/12736255/log.zip)

**Comment by shekhar16** [comment]
@manojs1978  it looks like source config's password is missing in jans-link configuration.

**Comment by manojs1978** [comment]
thank @shekhar16 , working fine
