### ISSUE TITLE
fix(admin-ui): large header issue

### ISSUE THREAD

**Issue by moabu** [GluuFederation/flex#1398]
**Describe the bug**

Looks like this is caused when a client has too many scopes stuffed in the jwt in the Authorization header, which causes the request header fields too large error

![image003](https://github.com/GluuFederation/flex/assets/47318409/a1806cac-455e-4141-b3bf-5a53870235c5)
![image002](https://github.com/GluuFederation/flex/assets/47318409/e5afaca4-61ee-444c-b8d0-b24527eb07aa)

**Comment by duttarnab** [comment]
Can welab team please share the authorization header.

**Comment by nynymike** [comment]
Please expedite this fix for the next release of Flex.

**Comment by duttarnab** [comment]
sure, we are working on this.

**Comment by duttarnab** [comment]
**Backend changes Update:** (https://github.com/JanssenProject/jans/issues/6413)

We have drafted a PR. The `/api-protection-token` has been modified. We have added a parameter called `permissionTag` (an array) to the request body. The endpoint will only add permissions (scopes) to the config-api token whose tags are included in the `permissionTag` parameter. This will help in including only the permissions in the token that are required for making a request. Hence, it will reduce the length of the token.


**Forntend changes required:**

The `front-end` (FE) will retrieve tags from a request-tag mapping configuration file and include them in the `permissionTag` parameter when making the request.

cc: @jv18creator

**Comment by jv18creator** [comment]
Admin UI will check for individual access token with `tag`, based on it, FE will call `/api-protection-token` which will generate `access_token` for specific permission. If there's already an `access_token` for that permission then we'll reuse that access token from redux store.
