### ISSUE TITLE
feat(flex-linux-setup): changes in admin-ui configuration and role_based_scopes script

### ISSUE THREAD

**Issue by duttarnab** [GluuFederation/flex#1410]
The below changes are required for following parent ticket# https://github.com/GluuFederation/flex/issues/1398

- [x] Change the `role_based_scopes` script  (`A44E-4F3D`) to the following attached.
[role_based_scope.txt](https://github.com/GluuFederation/flex/files/13191999/role_based_scope.txt)

- [x] In the `admin-ui` configuration replace the following permission in `permissions` array inside json object of `jansConfDyn` field.
[permissions.txt](https://github.com/GluuFederation/flex/files/13192048/permissions.txt)

![image](https://github.com/GluuFederation/flex/assets/32794267/c7449f9d-248d-4c27-af8b-afff223d2dfa)

**Comment by devrimyatar** [comment]
Requirments described in this issue is implemented in https://github.com/JanssenProject/jans/pull/6421
