### ISSUE TITLE
chore(admin-ui): add the missing TUI features in admin UI

### ISSUE THREAD

**Issue by duttarnab** [GluuFederation/flex#1414]
add the missing TUI features in admin UI

**Comment by jv18creator** [comment]
missing features in Admin UI
1. SCIM configuration module missing
![Screenshot 2023-11-01 at 8 57 36 AM](https://github.com/GluuFederation/flex/assets/64732692/9e3ca005-a22e-4740-9d0b-cec63f83de1e)
2. missing enable checkbox/switch on jans link inum db server
![Screenshot 2023-11-01 at 8 59 16 AM](https://github.com/GluuFederation/flex/assets/64732692/d8cd26c2-624f-4244-8a29-9d8a4dbb8c58)
3. missing module properties key/value pair input field (create/edit script form)
![Screenshot 2023-11-01 at 9 01 30 AM](https://github.com/GluuFederation/flex/assets/64732692/63cb557a-e78a-4c0c-98be-4a1f1b9aebd3)

**Comment by jv18creator** [comment]
few details are missed, following from the [thread](https://chat.gluu.org/group/service_admin_ui?msg=hXN8a7XBPjHSWRADx)

- change label of a field in Client / Token / Run Introspection Script Before AccessToken As Jwt Creation And Include Claims
- remove `subjectType` field from Client / Advanced Client Properties

**Comment by duttarnab** [comment]
done
