### ISSUE TITLE
fix(Admin-ui): lanuage translation

### ISSUE THREAD

**Issue by manojs1978** [GluuFederation/flex#1419]
**Describe the bug**
please change language translation according selected language

**To Reproduce**
1. install flex 5.0.0-20.nightly
2. check for below translations for other lanugages
![image](https://github.com/GluuFederation/flex/assets/5729240/57583bad-a945-44e9-bb0b-21432542149b)

**Expected behavior**
translation should be according to selected language

**Screenshots**

**Desktop (please complete the following information):**
  - OS: suse
  - Version 15 
  - flex 5.0.0-20.nightly
  - mysql

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jv18creator** [comment]
fixed in PR #1420
