### ISSUE TITLE
fix(admin-ui): able to add duplicate role

### ISSUE THREAD

**Issue by manojs1978** [GluuFederation/flex#1432]
**Describe the bug**
able to add duplicate role

**To Reproduce**
1.navigate to ADMIN>> Config-API >>Access Role and click on '+' icon (add role)
2. add duplicate role/already existing role 
3.add same description or anything with deletable true/false
4.click on yes option
Result:
expected Behaviour:- it should show message role already present
Actual :- it is showing  success msg and role not added to list

**Screenshots**
![image](https://github.com/GluuFederation/flex/assets/5729240/6a1a5be1-cb25-4d76-a4ad-b0e4d6790917)

**Desktop (please complete the following information):**
  - OS: ubuntu22
  - Version 22
  - DB mysql
  - flex 5.0.0-20.nightly

**Smartphone (please complete the following information):**

**Additional context**

**Comment by duttarnab** [comment]
done
