### ISSUE TITLE
fix(admin-ui): Not able to add multiple role

### ISSUE THREAD

**Issue by manojs1978** [GluuFederation/flex#1433]
**Describe the bug**
While Add Mapping not able to add multiple role for role field

**To Reproduce**
1..navigate to ADMIN>> Config-API>>Mapping and click on '+ Add Mapping'  tab
2.new role pop-up window show up
3.in role textbox it accept only one role which is mentioned in add role list 
4.Helper text shows "Enter multiple items by selecting from appeared dropdown after entering each item." 
5. user not able to add multiple role 

**Result:-**
Expected:- should able to add multiple roles 
Actual:- we can enter only one entry
 

**Screenshots**
![image](https://github.com/GluuFederation/flex/assets/5729240/f343e3e2-c44d-4257-a206-79df1f340888)

**Desktop (please complete the following information):**
OS:ubuntu 22
flex 5.0.0-20. nightly
DB mysql

**Smartphone (please complete the following information):**

**Additional context**

**Comment by duttarnab** [comment]
fixed
