### ISSUE TITLE
fix(admin-ui): Permission not getting added successfully

### ISSUE THREAD

**Issue by manojs1978** [GluuFederation/flex#1434]
**Describe the bug**
After adding permission comes with error pop-up messsege

**To Reproduce**
1. navigate to ADMIN>> Config-API>>permission and click on '+ ' icon
2.pou-up window comes up
3.add name and description 
4.click on yes button 

**Result:-**
expected:- permission should be added successfully and also get listed below
Actual:- error  pop-up messege comes 

**Screenshots**
![image](https://github.com/GluuFederation/flex/assets/5729240/bee4a6f3-74ef-44fb-a0df-44df593be764)

**Desktop (please complete the following information):**
OS:ubuntu 22
flex 5.0.0-20. nightly
DB mysql

**Smartphone (please complete the following information):**

**Additional context**

**Comment by duttarnab** [comment]
done
