### ISSUE TITLE
fix(admin-ui): admin/newly added user is not reflecting as active user in dashboard

### ISSUE THREAD

**Issue by manojs1978** [GluuFederation/flex#1446]
**Describe the bug**
admin user is not reflecting as active user in dashboard

**To Reproduce**
1. install flex 5.0.0-20.nightly
2. launch admin 
3. check active users
4. add new user and check active users

**Expected behavior**
admin should display as active user in dashboard when logged in for first time.
newly added user should reflect in active user instantly

**Screenshots**
![image](https://github.com/GluuFederation/flex/assets/5729240/0abc2a2a-0dc2-4394-a56d-383fda990e5f)
![image](https://github.com/GluuFederation/flex/assets/5729240/c20243e7-b648-4cd7-a7fe-c333d44d27cc)

**Desktop (please complete the following information):**
  - OS: ubuntu22
  - DB - mysql
  - flex 5.0.0-20.nighlty

**Smartphone (please complete the following information):**

**Additional context**

**Comment by duttarnab** [comment]
As discussed, it takes a while to populate data after installation.
