### ISSUE TITLE
fix(jans-tui): getting error in updating defaultpermissionin token in permissions

### ISSUE THREAD

**Issue by manojs1978** [GluuFederation/flex#1448]
**Describe the bug**
getting error in updating defaultpermissionin token in permissions

**To Reproduce**
1. install flex 5.0.0-20.nightly
2. launch tui
3. go to config-api >  permissions
4. edit any permission and update it
5. See error

**Expected behavior**
should able to update defaultpermission in token

**Screenshots**
![image](https://github.com/GluuFederation/flex/assets/5729240/ebd1a8da-f742-467f-9946-0b9c9cffd5e8)

**Desktop (please complete the following information):**
  - OS: suse
  - Version 15
  - flex 5.0.0-20.nightly
  - dbm mysql

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
suse-mysql database is not running propery due to json support.
