### ISSUE TITLE
feat(flex-linux-setup): replace jwt token with reference token to access config-api

### ISSUE THREAD

**Issue by duttarnab** [GluuFederation/flex#1456]
Parent issue # https://github.com/JanssenProject/jans/issues/6562

**ToDos:**

1. Remove `role_based_scopes` script from persistence. (**INUM**: A44E-4F3D)
2. Add the following `update_token` script to add permissions (scopes) into config-api access token.
[update_token_entry.txt](https://github.com/GluuFederation/flex/files/13367862/update_token_entry.txt)
[update-script.txt](https://github.com/GluuFederation/flex/files/13440824/update-script.txt)

3. Replace Admin UI Web Client with the following (there is change in client attributes).
[auiWebClient.txt](https://github.com/GluuFederation/flex/files/13367667/auiWebClient.txt)

4. Replace Admin UI Backend API client with the following.
[auiBackendApiClient.txt](https://github.com/GluuFederation/flex/files/13367848/auiBackendApiClient.txt)

5. Add `oidcConfig.auiBackendApiClient.introspectionEndpoint` containing introspection Endpoint of the OpenID provider in admin-ui configuration (`jansConfApp` field) 

![image](https://github.com/GluuFederation/flex/assets/32794267/34a39696-c669-461c-90be-d14e2eceea8c)

6. `oidcConfig.auiBackendApiClient.scopes` will have only `openid` scope in admin-ui configuration.
![image](https://github.com/GluuFederation/flex/assets/32794267/a57fa388-0ca9-4fff-985d-ac79ae36d92d)

**Comment by duttarnab** [comment]
cc: @iromli

**Comment by iromli** [comment]
@duttarnab waiting for https://github.com/GluuFederation/flex/pull/1470

cc @moabu
