### ISSUE TITLE
fix(custom-script): unable to get push notification on super gluu app

### ISSUE THREAD

**Issue by manojs1978** [GluuFederation/flex#1473]
**Describe the bug**
unable to get push notification on super gluu

**To Reproduce**
1. install 5.0.0.21.nightly
2. enable super_gluu in fido, add SSA in super_gluu custom script and enable it 
3. login to casa, register supergluu device 
4. enable other script like otp and enable 2FA in casa
5. set default auth as super_gluu
6. set preferred method as super_gluu in casa
7. relogin to jans-casa
8. See error

**Expected behavior**
should able to get push notification

**Screenshots**
![image](https://github.com/GluuFederation/flex/assets/5729240/8cc704fd-633b-42e9-9cb1-f929fa453bcd)

**Desktop (please complete the following information):**
  - OS: ubuntu22
  - flex 5.0.0.20
  - DB mysql

**Smartphone (please complete the following information):**

**Additional context**

**Comment by duttarnab** [comment]
I think this issue should be assigned to Super Gluu team.

**Comment by manojs1978** [comment]
working fine now
