### ISSUE TITLE
fix(admin-ui):instead of redirecting to admin page getting error when user logout 

### ISSUE THREAD

**Issue by manojs1978** [GluuFederation/flex#1509]
**Describe the bug**
instead of redirecting to admin page getting error when user logout 

**To Reproduce**
1. install flex 5.0.-21.nighlty
2. login admin
3. do some operations
4. loout for user
5. See error

**Expected behavior**
shold not get any error

**Screenshots**
![image](https://github.com/GluuFederation/flex/assets/5729240/4b935caa-cd77-4733-9803-4504d1f71b84)

**Desktop (please complete the following information):**
  - OS:ubuntu
-flex 5.0.21.nighlty
DB opendj

**Smartphone (please complete the following information):**

**Additional context**

**Comment by duttarnab** [comment]
Tested. Working in [v5.0.0-22.nightly](https://github.com/GluuFederation/flex/releases/tag/v5.0.0-22.nightly).
