### ISSUE TITLE
fix(admin-ui): getting unauthorized agent error pop up

### ISSUE THREAD

**Issue by manojs1978** [GluuFederation/flex#1522]
**Describe the bug**
getting unauthorized agent error pop

**To Reproduce**
1. login to admin
2. go to Authserver > configuration >SSA
3. click on SSA
4. See error pop up

**Expected behavior**
should not get any error

**Screenshots**
![image](https://github.com/GluuFederation/flex/assets/5729240/98927ca3-e1c6-4211-8458-57343abcdeb4)

**Desktop (please complete the following information):**
  - OS: ubuntu22
-flex 5.0.22.nighlty
db- opendj/mysql

**Smartphone (please complete the following information):**

**Additional context**

**Comment by duttarnab** [comment]
fixed
