### ISSUE TITLE
chore(flex-linux-setup): add ssa scope in Admin UI client

### ISSUE THREAD

**Issue by duttarnab** [GluuFederation/flex#1524]
Add `https://jans.io/auth/ssa.admin` scope to `auiBackendApiClient` (when flex installation is done).

![image](https://github.com/GluuFederation/flex/assets/32794267/78ab9d17-189c-4dd6-9547-77ed5ab3cb4e)

**Comment by iromli** [comment]
@duttarnab is this `https://jans.io/auth/ssa.admin` scope need to be added to https://github.com/GluuFederation/flex/blob/main/flex-linux-setup/flex_linux_setup/templates/auiConfiguration.json#L26 ?

**Comment by devrimyatar** [comment]
@duttarnab Where is **https://jans.io/auth/ssa.admin** defined? I were not be able to find it here https://github.com/JanssenProject/jans/blob/main/jans-config-api/server/src/main/resources/config-api-rs-protect.json

Should it be created it seperately?

**Comment by duttarnab** [comment]
Hi @devrimyatar 

`https://jans.io/auth/ssa.admin` is not a config-api scope, hence not present in https://github.com/JanssenProject/jans/blob/main/jans-config-api/server/src/main/resources/config-api-rs-protect.json. It is Jans-auth scope.

> Should it be created it separately?

yes, I believe we need to create it separately.

![image](https://github.com/GluuFederation/flex/assets/32794267/37dc3914-0363-4965-ae37-d4fa8fe61be9)

**Comment by duttarnab** [comment]
Hi @iromli 

> @duttarnab is this https://jans.io/auth/ssa.admin scope need to be added to https://github.com/GluuFederation/flex/blob/main/flex-linux-setup/flex_linux_setup/templates/auiConfiguration.json#L26 ?

There is no use in adding this scope to the configuration. We need this scope to access the following Auth Server API: 
`GET` https://admin-ui-test.gluu.org/jans-auth/restv1/ssa. This directly checks is the scope is present in client's scope attribtue.
So we just need to add the scope to the `auiBackendApiClient` client.

see code:
https://github.com/JanssenProject/jans/blob/main/jans-auth-server/server/src/main/java/io/jans/as/server/ssa/ws/rs/action/SsaGetAction.java#L95

![image](https://github.com/GluuFederation/flex/assets/32794267/06bd5e4d-6dff-4dd1-b5a3-ae6b106c1e7d)

**Comment by devrimyatar** [comment]
As @iromli noted (https://github.com/GluuFederation/flex/pull/1526#issuecomment-1872654642) we have https://jans.io/auth/ssa.admin scope in https://github.com/JanssenProject/jans/blob/main/jans-linux-setup/jans_setup/templates/scopes.ldif#L233-L241
