### ISSUE TITLE
feat(admin-ui): implement short codes in webhooks to pass dynamic info on webhook execution

### ISSUE THREAD

**Issue by jv18creator** [GluuFederation/flex#1542]
- Add `short codes` in webhook url & request body when creating/updating a webhook.
- Trigger webhook & replace the short codes from url/request body using the success response of an event.

Parent ticket# https://github.com/GluuFederation/flex/issues/1503

![Screenshot 2024-01-17 at 11 46 33 AM](https://github.com/GluuFederation/flex/assets/64732692/22ba3674-1c78-48ec-9898-ce3fc2ca176f)

**Comment by duttarnab** [comment]
**Notes:**
1. Admin UI has features to add/edit/delete scopes, oidc clients, attributes, users etc.
2. The created webhook can be mapped with these Admin UI features, which means that the webhook will be triggered on execution of the feature event (to which it is mapped).
3. Each Admin feature will have its pre-defined set of short-codes which can be added to the request-body or url of the webhook.
4. On triggering the webhooks the short-code will be replaced by the actual values by the UI.
5. There can be only one to one mapping between webhook and Admin feature (to prevent incorrect swapping of short-codes with another feature's webhook).
