### ISSUE TITLE
fix(admin-ui): oxAuth login page "Forgot Password" link should point to proper password renew page for jans

### ISSUE THREAD

**Issue by mzico** [GluuFederation/flex#1550]
oxAuth login page has link "Forgot your password" which is forwarding user to oxtrust passwordReminder page ( https://xxxxx/identity/person/passwordReminder.htm ). We should make this workable for Jans. 
![Password_reset](https://github.com/GluuFederation/flex/assets/7156097/6a165721-8ac7-414f-a624-22aa7b589a21)

**Comment by duttarnab** [comment]
This login page is present in auth server project. The `Forgot password` link has been removed from the latest installation.

![image](https://github.com/GluuFederation/flex/assets/32794267/5463fd57-426c-44c3-b477-07e3011ac761)

Closing the issue.
