### ISSUE TITLE
fix(admin-ui): getting upload ssa creen

### ISSUE THREAD

**Issue by manojs1978** [GluuFederation/flex#1551]
**Describe the bug**
getting upload ssa creen

**To Reproduce**
1. install flex  with valid SSA
2. launch admin-ui

**Expected behavior**
should able to login admin ui

**Screenshots**
![image](https://github.com/GluuFederation/flex/assets/5729240/508a91ae-c49b-4e6c-9b04-95e8e1d1716e)
**Desktop (please complete the following information):**
  - OS: ubuntu22
-flex 5.0.22.nightly
-opendj

**Smartphone (please complete the following information):**

**Additional context**

**Comment by duttarnab** [comment]
this has been already fixed.
