### ISSUE TITLE
fix(admin-ui): unable to create or see user details

### ISSUE THREAD

**Issue by manojs1978** [GluuFederation/flex#1566]
**Describe the bug**
unable to create or see user details

**To Reproduce**
1. install flex 5.0.22.nighlty
2. launch admin 
3. create new user or check for existing users

**Expected behavior**
unable to create new user or see existing one

**Screenshots**
![image](https://github.com/GluuFederation/flex/assets/5729240/fad02721-247d-404e-9763-142bf74871b5)
![image](https://github.com/GluuFederation/flex/assets/5729240/1b82639a-3cbf-488f-8be0-2fe3d9a9b279)

**Desktop (please complete the following information):**
  - OS: ubuntu22
  - flex 5.0.22.nihglty
  - DB mysql

**Smartphone (please complete the following information):**

**Additional context**

**Comment by duttarnab** [comment]
Fixed.
