### ISSUE TITLE
fix(admin-ui): unable to load casa script in admin

### ISSUE THREAD

**Issue by manojs1978** [GluuFederation/flex#1569]
**Describe the bug**
unable to load casa script in admin

**To Reproduce**
1. install flex 5.0.0-22.nighlty
2. login admin ui
3. check casa script

**Expected behavior**
should not get any error for casa script opening

**Screenshots**
![image](https://github.com/GluuFederation/flex/assets/5729240/451687bd-ff24-4103-a8f4-2afb527d9555)
![image](https://github.com/GluuFederation/flex/assets/5729240/1dbead76-81f3-4166-b268-1045d80fcc9f)

**Desktop (please complete the following information):**
  - OS: ubuntu22
  - flex 5.0.0-22.nighlty
  - DB mysql

**Smartphone (please complete the following information):**

**Additional context**

**Comment by duttarnab** [comment]
@manojs1978 this is not an Admin UI issue. We need check if there is not error in Casa script.
cc: @jgomer2001

**Comment by jgomer2001** [comment]
will get fixed when this one is closed: https://github.com/JanssenProject/jans/issues/7666

**Comment by jgomer2001** [comment]
done
https://github.com/JanssenProject/jans/pull/7684
