### ISSUE TITLE
Front channel logout uri is not displayed

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/flex#157]
A Client having `jansLogoutURI` populated  does not show anything in the form field  "Front Channel Logout URI"

**To Reproduce**
Install flex using a **MySQL** backend
Visit the admin ui
See the details of a client such as "Casa" or "Jans Role Based Client"

**Expected behavior**
Logout uris shown

**Desktop (please complete the following information):**
  - OS: Ubuntu 18
  - Browser Oopera

**Comment by duttarnab** [comment]
Fixed
