### ISSUE TITLE
fix(admin-ui): Error in retrieving license

### ISSUE THREAD

**Issue by manojs1978** [GluuFederation/flex#1573]
**Describe the bug**
Error in retrieving license

**To Reproduce**
1. install flex
2. launch admin
3.  See error

**Expected behavior**
should able to get login

**Screenshots**
![image](https://github.com/GluuFederation/flex/assets/5729240/fe4a72b9-8f45-4b77-8c90-0fb143b1aa70)

**Desktop (please complete the following information):**
  - OS: suse 15
  - flex 5.0.22
  - DB opendj

**Smartphone (please complete the following information):**

**Additional context**
[adminui.log](https://github.com/GluuFederation/flex/files/14280267/adminui.log)
[adminuiAudit.log](https://github.com/GluuFederation/flex/files/14280268/adminuiAudit.log)

[manojs1978-loved-coyote.gluu.info.har.txt](https://github.com/GluuFederation/flex/files/14280261/manojs1978-loved-coyote.gluu.info.har.txt)

**Comment by duttarnab** [comment]
Fix has been implemented in SCAN license APIs.
