### ISSUE TITLE
feat(admin-ui): shift `SESSION_TIMEOUT_IN_MINUTES` to admin-ui configuration in persistence

### ISSUE THREAD

**Issue by duttarnab** [GluuFederation/flex#1575]
Currently, Admin UI session time-out is present in `.env` file. So it is not possible for user to change timeout in Admin UI. 

The solution is to place this field in Admin UI configuration so the user can change it (whenever required).

https://github.com/GluuFederation/flex/blob/main/admin-ui/.env.tmp#L5

![image](https://github.com/GluuFederation/flex/assets/32794267/f6678220-3370-4b6e-8e9d-4d5b3c5337a6)

**Comment by duttarnab** [comment]
Add screens to set acr values and session-timeout from UI.

**Comment by ossdhaval** [comment]
@duttarnab It looks like this change may require a documentation update as well. Please evaluate the documentation aspect and make the change along with the code change within this PR itself.

**Comment by duttarnab** [comment]
@ossdhaval Thanks for raising this point. I just raised another issue for docs as I was working on it parallelly.  Kindly review it whenever possible.

PR : https://github.com/GluuFederation/flex/pull/1583

**Comment by ossdhaval** [comment]
> @ossdhaval Thanks for raising this point. I just raised another issue for docs as I was working on it parallelly. Kindly review it whenever possible.
> 
> PR : #1583

approved :heavy_check_mark:
