### ISSUE TITLE
feat: implement a method to override the default connection params for the admin ui

### ISSUE THREAD

**Issue by moabu** [GluuFederation/flex#1576]
We need to implement a method to be able to pass and override the URLs  in the admin ui used to connect to the backend services such as the config API . This is to be able to make the calls without directly hitting the FQDN ( Through the internet). 

We should default them but allow override at https://github.com/GluuFederation/flex/blob/main/flex-linux-setup/flex_linux_setup/templates/auiConfiguration.json

**Comment by duttarnab** [comment]
Following feat has been implemented in Admin UI.
https://github.com/GluuFederation/flex/issues/1594

**Comment by duttarnab** [comment]
![Clipboard - March 14, 2024 11_49 AM (1)](https://github.com/GluuFederation/flex/assets/32794267/5e41842f-fc16-40c5-b4de-19258f963599)


https://chat.gluu.org/group/product_flex?msg=tH2EgnYK5C6XBdMSE
