### ISSUE TITLE
feat(flex-linux-setup): add sessionTimeoutInMins in admin-ui configuration

### ISSUE THREAD

**Issue by duttarnab** [GluuFederation/flex#1577]
parent issue# https://github.com/GluuFederation/flex/issues/1575

Add 

```
 "uiConfig":{"sessionTimeoutInMins": 30}
```

to 

https://github.com/GluuFederation/flex/blob/main/flex-linux-setup/flex_linux_setup/templates/auiConfiguration.json

**Comment by duttarnab** [comment]
Hi @iromli, kindly replicate this change to k8 setup.

**Comment by iromli** [comment]
@duttarnab sure, i will take a look
