### ISSUE TITLE
Client secret and front channel logout uri disappear after client edition

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/flex#158]
**Describe the bug**
Editing a client to turn off/on the "skip authorization flow" degenerates in  the client secret `jansClntSecret` and logout uri `jansLogoutURI` being wiped

**To Reproduce**
Install flex using a **MySQL** backend
Visit the admin ui
Open the details of "Casa" client 
Turn off the "skip" switch and apply changes
The client secret is gone (in UI and database), and the logout URI is gone in database

**Expected behavior**
No data loss

**Desktop (please complete the following information):**
  - OS: Ubuntu 18
  - Browser Opera

**Additional context**
[Related issue](https://github.com/GluuFederation/flex/issues/157)

**Comment by duttarnab** [comment]
Done
