### ISSUE TITLE
feat(admin-ui): manage custom assets screens in admin ui

### ISSUE THREAD

**Issue by duttarnab** [GluuFederation/flex#1635]
**Usecase**
There should be a clear non filesystem (volume) based solution for possible user customization's such as login pages, CSS, libraries ..etc. Managed clearly by an API endpoint then further optimized by drag and drop in a parent admin ui.

https://raw.githubusercontent.com/JanssenProject/jans/main/jans-config-api/docs/jans-config-api-swagger.yaml

![image](https://github.com/GluuFederation/flex/assets/32794267/f788a2dd-a099-4ce0-81bf-15f84d0494ed)

**Ref issues**
https://github.com/JanssenProject/jans/issues/7932
https://github.com/JanssenProject/jans/issues/2419

Subtask:
-----------
- [ ] #1651

**Comment by syntrydy** [comment]
![image](https://github.com/GluuFederation/flex/assets/7513418/b9fbe62e-1186-44c1-8c10-9c852119fceb)
![image](https://github.com/GluuFederation/flex/assets/7513418/bea7160a-1c4c-433a-8e06-ab2c4c90beb7)
![image](https://github.com/GluuFederation/flex/assets/7513418/253758d3-47ae-465f-b1e0-7e880942f787)
