### ISSUE TITLE
bug(admin-ui): Admin UI is not able to display user status in v5.1.1

### ISSUE THREAD

**Issue by mzico** [GluuFederation/flex#1677]
We can set status when creating users on Admin UI, and are able to edit status, but when browsing the created users, there is no status displayed, 

Image version of Admin UI: 5.1.1-1 Chart version: admin-ui-5.1.1

All other components: Image version: 1.1.1-1 Chart version: {{component}}-1.1.1

Can we try to check if it's happening in latest build?  I ( will ) try to setup a testbed ( for upgrade ) and re-test. 

@jv18creator : please re-assign this issue to me after you done checking default standalone 5.1.1 or above.

**Comment by jv18creator** [comment]
@mzico I have done a fresh install today & the status seems to be displayed as expected.


https://github.com/GluuFederation/flex/assets/64732692/695e877d-dc7c-4998-8c4e-ce7b0a270cb4

**Comment by duttarnab** [comment]
This issue has been fixed.
