### ISSUE TITLE
Admin-UI : upon click on enter key in OCID new entry the form getting submitted.

### ISSUE THREAD

**Issue by mjatin-dev** [GluuFederation/flex#169]
<img width="973" alt="Screenshot 2022-03-21 at 9 20 42 PM" src="https://user-images.githubusercontent.com/32476704/159299086-862b9449-07cc-4313-8f8f-7259e23a29fb.png">
Upon click on enter on this above page. page should not be getting submitted as there are another tabs for user to go discover

**Comment by duttarnab** [comment]
Done
