### ISSUE TITLE
fix(admin-ui): unable to re-upload SSA

### ISSUE THREAD

**Issue by manojs1978** [GluuFederation/flex#1695]
**Describe the bug**
unable to re-upload SSA

**To Reproduce**
1. install flex 5.1.2.nighlty
2. launch admin 
3. upload invalid SSA
4. check how to upload new SSA

**Expected behavior**
there should be way to re-upload new SSA

**Screenshots**

**Desktop (please complete the following information):**
  - OS:ubuntu22
  - fle 5.1.2.nightly
  - DB opendj

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jv18creator** [comment]
I am able to re-upload the .jwt file.

https://github.com/GluuFederation/flex/assets/64732692/7685dca6-a5d1-4ce1-ae9f-b15372ddb12b

**Comment by manojs1978** [comment]
https://github.com/GluuFederation/flex/assets/5729240/95d6723a-8cbc-4bd4-90cc-0fc72d38150d

when we uploaded expired SSA in that case we are not able to upload new SSA

**Comment by duttarnab** [comment]
@manojs1978 could you share the invalid ssa you uploaded

**Comment by manojs1978** [comment]
shared with @jv18creator

**Comment by jv18creator** [comment]
Hi @manojs1978 I used the ssa which you shared earlier but the api throws 500 error instead of 201 success.

https://github.com/GluuFederation/flex/assets/64732692/3b182c32-fb26-48a8-9f0e-d37d52a3679e
