### ISSUE TITLE
fix(admin-ui): the displayed error message is not clear when adding duplicate user

### ISSUE THREAD

**Issue by duttarnab** [GluuFederation/flex#1723]
When creating the user with already existing email or username, the displayed error message is not clear.

The error message should clearly mention username or email matches with credentials of the user existing in database.
![image](https://github.com/GluuFederation/flex/assets/32794267/f38ef143-cef7-4050-adf5-4a9861cdad0e)

![image](https://github.com/GluuFederation/flex/assets/32794267/a76cccd7-1803-4a60-8393-56e0e2f6f335)

**Comment by jv18creator** [comment]
Hi @pujavs as discussed earlier on chat, we get this odd error message when duplicate username is added. Have a look when you're available and try to update the error format for better UX.

**Comment by duttarnab** [comment]
@jv18creator what is the status

**Comment by jv18creator** [comment]
@duttarnab as mentioned [here](https://chat.gluu.org/group/service_admin_ui?msg=YS6Bk7b7kDyX2Szxp),  I was not able to see the config api changes, I will check out TUI on a new vm and update you.
