### ISSUE TITLE
fix(admin-ui): blank page after deploying SSA

### ISSUE THREAD

**Issue by manojs1978** [GluuFederation/flex#1724]
**Describe the bug**
blank page after deploying SSA

**To Reproduce**
1. install 5.1.2.nightly
2. deoply SSA

**Expected behavior**
should get admin ui dashboard

**Screenshots**
![image](https://github.com/GluuFederation/flex/assets/5729240/f2d5c037-4b75-4277-92a8-2603dea143a7)

**Desktop (please complete the following information):**
  - OS: ubuntu22
-flex 5.1.2.nightly
-db opendj
**Smartphone (please complete the following information):**

**Additional context**
[log.zip](https://github.com/GluuFederation/flex/files/15451743/log.zip)

**Comment by duttarnab** [comment]
@jv18creator is it done

**Comment by jv18creator** [comment]
@duttarnab I was not able to reproduce it. @manojs1978 any update after [this discussion](https://chat.gluu.org/group/service_admin_ui?msg=ExuLXp6fKLdNiartp)?

**Comment by manojs1978** [comment]
no as i told ,
this issue might be due to  jans-auth issue  on that particular date.

now it is not reproduced. we can close
