### ISSUE TITLE
fix(admin-ui): getting error while flex installation

### ISSUE THREAD

**Issue by manojs1978** [GluuFederation/flex#1738]
**Describe the bug**
getting error while flex installation

**To Reproduce**
1. install flex 5.1.2.nightly

**Expected behavior**
shouldnot get any error

**Screenshots**
![image](https://github.com/GluuFederation/flex/assets/5729240/a5324f6d-6cac-4c09-8d1d-e7102a2a99ee)

**Desktop (please complete the following information):**
  - OS: ubuntu22
-flex  5.1.2.nightly
-DB opendj
**Smartphone (please complete the following information):**

**Additional context**

**Comment by duttarnab** [comment]
Fixed
