### ISSUE TITLE
We should be able to add multiple items to Spontaneous Client Scopes:

### ISSUE THREAD

**Issue by mjatin-dev** [GluuFederation/flex#174]
1. We should be able to add multiple items to Spontaneous Client Scopes:
2. The edit scope option should works with all the values. as of now selected `Spontaneous Client Scopes` are not showing to the user while edit.
![Clipboard - March 24, 2022 9_36 PM](https://user-images.githubusercontent.com/32476704/160811476-eb8f5ed5-8399-45e0-a291-07ebe4aadf9d.png)

**Comment by duttarnab** [comment]
Done
