### ISSUE TITLE
fix(jans-cli-tui): TUI breaking while searching scripts

### ISSUE THREAD

**Issue by manojs1978** [GluuFederation/flex#1760]
**Describe the bug**
TUI breaking while searching scripts

**To Reproduce**
1. install flex 5.1.3.nighly
2. login server , and launch TUI
3. Search for script

**Expected behavior**
should not break TUI

**Screenshots**
![image](https://github.com/GluuFederation/flex/assets/5729240/ad05968b-dac9-4e90-b9f2-2baa9c92280f)

**Desktop (please complete the following information):**
  - OS: ubuntu22
  - pgsql

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
@manojs1978 I were not be able to replicate. Please re-test.
