### ISSUE TITLE
fix: Duo script is missing form flex

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [GluuFederation/flex#1761]
**Describe the bug**
Duo script is missing form flex 

**To Reproduce**
1. install flex 5.1.3.nighly
2. login server , and launch admin UI
3. Search for script

**Expected behavior**
duo script must appear 

**Screenshots**
![Screenshot (69)](https://github.com/GluuFederation/flex/assets/34593983/be6496e7-35a0-4ef2-b5b9-79d936a8800c)

**Desktop (please complete the following information):**
  - OS: ubuntu22
  - Version 5.1.3
  - pgsql

**Additional context**

**Comment by duttarnab** [comment]
Duo script is not present in persistence.

![image](https://github.com/GluuFederation/flex/assets/32794267/1a509f38-d04e-4065-a677-88f10b65388d)

**Comment by MohitMaliFtechiz** [comment]
@duttarnab yes i just checked it it is not present, In jans installation it is available, but on flex installation it is missing.

**Comment by devrimyatar** [comment]
We do remove DUO scprit

![image](https://github.com/GluuFederation/flex/assets/6398752/7b894d0f-a67a-49aa-8395-bc092556e163)

**Comment by devrimyatar** [comment]
See issue https://github.com/GluuFederation/flex/issues/1120
