### ISSUE TITLE
fix(admin-ui): Enhancements and Bugfixes in SAML SP Management.

### ISSUE THREAD

**Issue by uprightech** [GluuFederation/flex#1764]
On the `SAML` > `Website SSO` > `Create / Edit Service Provider` screen , there are some changes to be made. 
![flex-fixes](https://github.com/GluuFederation/flex/assets/725670/1e9ba0d1-c7fe-4258-bdd9-f853f992736c)
- The "description" field ought to be optional
- Remove the "Surrogate Auth Required" field
- Remove the "Root URL" field
- Remove the "Admin URL" field
- The "Released Attributes" lists scopes instead of attributes. It should list attributes (see the same functionality in jans-cli-tui for reference)

**Comment by mjatin-dev** [comment]
@uprightech @duttarnab 

In SAML service provide when we choose Metadata locatin type to manual then single logut serive url, entity id input and other inputs will appear. if haven't fill these details then we got error from backend.

**I think we need to make is field as required input when Metadata locations is manual currently these are not.**
![image](https://github.com/user-attachments/assets/10d6c601-3b70-46bf-b2be-be459cab30db)

**Comment by duttarnab** [comment]
The underlying fields will be mandatory when Metadata Location type to manual.
