### ISSUE TITLE
feat(admin-ui):UI for managing Config API configuration properties 

### ISSUE THREAD

**Issue by pujavs** [GluuFederation/flex#1779]
Need UI to mange Config API configuration properties in line with Jans Auth-Server configuration properties
Endpoint `[/api/v1/api-config`

Check swagger spec for details:
![image](https://github.com/JanssenProject/jans/assets/43700552/7eaa5980-ed98-432d-81f4-1cb1acb0e0aa)

Do not allow update of following fields:

- `apiProtectionType`
- `apiClientId`
- `apiClientPassword`
- `endpointInjectionEnabled`
- `authIssuerUrl`
- `authOpenidConfigurationUrl`
- `authOpenidIntrospectionUrl`
- `authOpenidTokenUrl`
- `authOpenidRevokeUrl`
- `exclusiveAuthScopes`
- `corsConfigurationFilters`****

**Comment by duttarnab** [comment]
this task has been already addressed under: https://github.com/GluuFederation/flex/issues/1621
