### ISSUE TITLE
fix(admin-ui):Adding assets is getting 500 error.

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [GluuFederation/flex#1798]
**Describe the bug**
Adding assets is getting 500 error.

**To Reproduce**
1. install flex
2. go to admin
2. add new asset
3. add properties file in jans-auth

**Expected behavior**

should not get any error

**Screenshots**

**Desktop (please complete the following information):**
  - OS: ubuntu22 
  - Version sp5
  - flex 5.1.4.nightly
  - DB opendj

**Smartphone (please complete the following information):**

**Additional context**

![Screenshot (98)](https://github.com/user-attachments/assets/8fda6c00-ed40-4a8d-ad38-9cb1dd9e13fa)

**Comment by manojs1978** [comment]
![image](https://github.com/user-attachments/assets/e318494b-f15a-42cc-83a7-9a570b322664)
working on TUI

**Comment by duttarnab** [comment]
Fixed in recent build.
