### ISSUE TITLE
fix(admin-ui): search is not working in claims section of edit user.

### ISSUE THREAD

**Issue by mjatin-dev** [GluuFederation/flex#1810]
**Describe the bug**
Search is not working in claims section of edit user.

**To Reproduce**
1. Go to users
2. Click on on edit user
3. Scroll down to Available Claims and search any claims
4. See error - (search is not working in claims)

**Expected behavior**
When search a claims "user_name" it will show particular claim.

**Screenshots**
![image](https://github.com/user-attachments/assets/01b41809-5100-435a-b193-f08eacc4893a)

**Comment by duttarnab** [comment]
It is working in the latest release.
