### ISSUE TITLE
fix(admin-ui): unable to update Admin-ui feature in webhook

### ISSUE THREAD

**Issue by manojs1978** [GluuFederation/flex#1860]
**Describe the bug**
unable to update Admin-ui feature 

**To Reproduce**
1. install flex 5.1.6.nightly
2. login and create new webhook with some value
3. update admin-ui feature

**Expected behavior**
should able to update admin-ui feature field

**Screenshots**
![image](https://github.com/user-attachments/assets/449613d8-9c02-4e6d-82d1-84b0ff40294e)

**Desktop (please complete the following information):**
  - OS: ubuntu22
-flex 5.1.6.nightly
-DB pgsql

**Smartphone (please complete the following information):**

**Additional context**

https://github.com/user-attachments/assets/43b24790-5cf5-4292-818d-ddeed0b27d3b

**Comment by duttarnab** [comment]
Fixed
