### ISSUE TITLE
fix(admin-ui): updating asset showing 500 error

### ISSUE THREAD

**Issue by manojs1978** [GluuFederation/flex#1861]
**Describe the bug**
update asset giving 500 error

**To Reproduce**
1. install flex 5.1.6.nightly
2. login to admin ui
3. click asset in admin
4. upload new asset of png file in jans-auth
5. edit uploaded asset and modify file , name and relative service 
6. save changes
7. See error

**Expected behavior**
should not get any error

**Screenshots**
![image](https://github.com/user-attachments/assets/bcc3b972-b2c7-4f44-abe3-d615e1274a88)

**Desktop (please complete the following information):**
  - OS: suse
-flex 5.1.6.nightly
-DB pgsql

**Smartphone (please complete the following information):**

**Additional context**

https://github.com/user-attachments/assets/6de03db1-9c2b-42d6-8226-f41b39d0a9b7

**Comment by pujavs** [comment]
@manojs1978 for `jans-lock` the config is avialable only for asset type `.jar`. You can confirm this either from any UI or from source code -> https://github.com/JanssenProject/jans/blob/main/jans-linux-setup/jans_setup/templates/jans-config-api/dynamic-conf.json#L78-L296

Request you to please try uploading a jar file. I will also update the error message to indicate the same.

- Testing
![image](https://github.com/user-attachments/assets/6ca88253-086b-41f7-a8a8-912bdb1b2697)

**Comment by pujavs** [comment]
Made error message descriptive via  PR [9919] (https://github.com/JanssenProject/jans/pull/9919)

- FYI
![image](https://github.com/user-attachments/assets/979450c8-3351-4e69-80a3-167c542482ab)

**Comment by pujavs** [comment]
@manojs1978, request you to please verify and confirm

**Comment by manojs1978** [comment]
ok checking

**Comment by duttarnab** [comment]
Fixed.
