### ISSUE TITLE
feat(admin-ui): display status of Auth Server, Config API, FIDO, Casa, Keycloak, SCIM on Dashboard.

### ISSUE THREAD

**Issue by duttarnab** [GluuFederation/flex#1863]
<img width="831" alt="image" src="https://github.com/user-attachments/assets/5cd0c8ac-c39a-44ef-8e43-1b59ee08329e">

**Comment by duttarnab** [comment]
Done

**Comment by mjatin-dev** [comment]
Need to create resposive design as well
