### ISSUE TITLE
fix(admin-ui): Error in generating token to access Jans Config Api

### ISSUE THREAD

**Issue by manojs1978** [GluuFederation/flex#1889]
**Describe the bug**
Error in generating token to access Jans Config Api

**To Reproduce**
1.install flex 5.1.6.nightly
2. launch admin ui

**Expected behavior**
should not get any error

**Screenshots**
![image](https://github.com/user-attachments/assets/9469d2dc-2c5e-41dc-b62f-40e5fceb0b01)

**Desktop (please complete the following information):**
  - OS:ubuntu22
-DB mysql
**Smartphone (please complete the following information):**

**Additional context**
[jans-auth.zip](https://github.com/user-attachments/files/17783794/jans-auth.zip)
[config-api.zip](https://github.com/user-attachments/files/17783795/config-api.zip)

**Comment by duttarnab** [comment]
fixed
