### ISSUE TITLE
fix(admin-ui): lic details page showing error "The License API is not enabled for this application."

### ISSUE THREAD

**Issue by manojs1978** [GluuFederation/flex#1892]
**Describe the bug**
 lic details page showing error "The License API is not enabled for this application."

**To Reproduce**
1. install flex 5.1.6.nightly
2. login admin ui
3. check lic details page

**Expected behavior**
should not get any error

**Screenshots**
![image](https://github.com/user-attachments/assets/b1670437-3c50-4bd9-a0f4-73955ee54372)

**Desktop (please complete the following information):**
  - OS: ubuntu22
  - DB mysql

**Smartphone (please complete the following information):**

**Additional context**

**Comment by duttarnab** [comment]
fixed. https://chat.gluu.org/group/service_admin_ui?msg=5jkKtafDzL4FQFZ8j
