### ISSUE TITLE
fix(admin-ui): unable to select search scope

### ISSUE THREAD

**Issue by manojs1978** [GluuFederation/flex#1899]
**Describe the bug**
unable to select search scope

**To Reproduce**
1. install flex 5.1.6.nightly
2. create auth client
3. search for openid scope and try to add 

**Expected behavior**
should able to search and select scope

**Screenshots**
![image](https://github.com/user-attachments/assets/fc3be7c3-3ab4-4503-83b8-e32838bdded7)

**Desktop (please complete the following information):**
  - OS: ubuntu 22
flex  5.1.6.nightly
DB- mysql

**Smartphone (please complete the following information):**

**Additional context**

https://github.com/user-attachments/assets/f18327be-ec6b-418c-b2d2-e75f5dbd4e41

**Comment by duttarnab** [comment]
Unable to reproduce this issue.
