### ISSUE TITLE
feat(admin-ui): Setup relative path 

### ISSUE THREAD

**Issue by harryandriyan** [GluuFederation/flex#191]
### Description

- Development target issue
  We need to define the relative path to make the import section code clean and easy to manage
for example importing `../../utils/TokenController` 
we can make it `import { someFunc } from Utils/TokenController`

- Implementation Details
Define relative path in webpack config and use it on import modules

-------------------

### Prepare

- [x] Read contribution guidelines
- [x] Read license information

### Reference
https://dev.to/georgedoescode/simplify-your-imports-with-webpack-aliases-59f

**Comment by duttarnab** [comment]
Done
