### ISSUE TITLE
fix(admin-ui): smtp test failing

### ISSUE THREAD

**Issue by manojs1978** [GluuFederation/flex#1919]
**Describe the bug**
smtp test failing

**To Reproduce**
1. install flex 5.1.6
2. configure smtp server  for starttls with 465 port
3. test configuration

**Expected behavior**
test configuration should work 

**Screenshots**
![image](https://github.com/user-attachments/assets/296d1e49-95ae-49ab-a1cd-6804b74e36f8)

**Desktop (please complete the following information):**
  - OS:ubuntu22
-flex 5.1.6
DB mysql

**Smartphone (please complete the following information):**

**Additional context**

**Comment by duttarnab** [comment]
The SMTP is working when tested. 
<img width="815" alt="image" src="https://github.com/user-attachments/assets/9ce348e5-049d-4adf-b4c4-98ac80d79446" />
