### ISSUE TITLE
feat(admin-ui): Use efficient way to import lodash library

### ISSUE THREAD

**Issue by harryandriyan** [GluuFederation/flex#192]
### Description

- Development target issue
  Avoid importing whole lodash library `import _ from 'lodash'`
Alternative, we can import specific method of the lodash library
`import map from 'lodash/map'`

- Implementation Details
Change all import all modules lodash library 

-------------------

**Comment by harryandriyan** [comment]
PR: https://github.com/GluuFederation/flex/pull/199
@duttarnab

**Comment by duttarnab** [comment]
Done
