### ISSUE TITLE
feat(admin-ui): Deprecated createStore method in Redux

### ISSUE THREAD

**Issue by harryandriyan** [GluuFederation/flex#193]
### Description

- Development target issue
We recommend using the `configureStore` method of the @reduxjs/toolkit package, to replaces `createStore`.

Redux Toolkit is our recommended approach for writing Redux logic today, including store setup, reducers, data fetching, and more.

- Implementation Details
Replace `createStore` with `configureStore` and make sure all functionality still 100% properly working

<img width="932" alt="Screen Shot 2022-06-07 at 15 10 25" src="https://user-images.githubusercontent.com/7929947/172330023-d5fffe35-c1b5-4a9b-a744-8aa392775959.png">

**Comment by duttarnab** [comment]
Done
