### ISSUE TITLE
feat(flex-linux-setup): using `agama_io.jans.casa.authn.main` as default acr in admin-ui

### ISSUE THREAD

**Issue by duttarnab** [GluuFederation/flex#1935]
- [x] We are thinking to use casa agama project (`io.jans.casa.authn.main`) also for admin-ui authentication as the project is included by default in flex installation.

**Comment by duttarnab** [comment]
cc: @iromli

**Comment by iromli** [comment]
@duttarnab as `agama_io.jans.casa.authn.main` relies on optional casa installation (and its service being up and running), we should not set the ACR as default.

**Comment by iromli** [comment]
in cloud-native, we enable casa by default. @devrimyatar can you confirm that casa is enabled by default in linux-setup?

**Comment by duttarnab** [comment]
> @duttarnab as agama_io.jans.casa.authn.main relies on optional casa installation (and its service being up and running), we should not set the ACR as default.

Noted, reopening the issue to revert the changes.
