### ISSUE TITLE
feat(flex-linux-setup): include casa agama project in flex installation even if casa is not installed

### ISSUE THREAD

**Issue by duttarnab** [GluuFederation/flex#1938]
- [ ] Now Admin UI is using casa project for authentication. We need to include casa agama project in flex installation even if casa is not installed.

Agama project: https://github.com/GluuFederation/agama-casa

<img width="1176" alt="image" src="https://github.com/user-attachments/assets/77730fb6-7de3-4f88-b26b-5b30e572a898" />

**Comment by devrimyatar** [comment]
@duttarnab I need insruction to deploy amaga-casa project without installing casa.

**Comment by duttarnab** [comment]
The Agama project :`https://github.com/GluuFederation/agama-casa` is used by Casa for authentication. However, I believe this project is not deployed on the Jans server by the flex installer if Casa is not installed. Since we have now started using agama-Casa for Admin UI authentication, the installer should deploy agama-Casa in a Flex installation that includes Admin UI (even if Casa is not installed).

**Comment by devrimyatar** [comment]
As @jgomer2001 commented in RC, agama-casa project requires casa. So this issue becomes non-relevant.

![Screenshot_2024_1230_183301](https://github.com/user-attachments/assets/cc5c0b17-e4de-4594-9f45-2d1f9a4c2e8f)
