### ISSUE TITLE
fix(admin-ui): unable to login admin-ui

### ISSUE THREAD

**Issue by manojs1978** [GluuFederation/flex#1942]
**Describe the bug**
unable to login admin-ui

**To Reproduce**
1. install flex nightly  build
2. launch admin ui
3. deploy SSA file and wait for login page

**Expected behavior**
should able to login

**Screenshots**
![image](https://github.com/user-attachments/assets/fc33ee73-86a3-4e26-b023-f2bf477d53ec)

**Desktop (please complete the following information):**
  - OS: ubuntu22
-flex nightly
-DB pgsql

**Smartphone (please complete the following information):**

**Additional context**

in url getting below error
```
https://manojs1978-touching-shad.gluu.info/admin/?reason=Unable+to+find+script+for+acr%3A+%5Bio.jans.casa.authn.main%5D.+Send+error%3A+unmet_authentication_requirements&error_description=The+Authorization+Server+is+unable+to+meet+the+requirements+of+the+Relying+Party+for+the+authentication+of+the+End-User.+OP+is+unable+to+use+acr+specified+in+request.+CorrelationId%3A+7b9ae334-41d0-4117-9f0b-0de056706804&state=4mdC1GLaVy&error=unmet_authentication_requirements
```

**Comment by duttarnab** [comment]
fixed
