### ISSUE TITLE
Admin UI: MAU - Date range showing undefined and ?

### ISSUE THREAD

**Issue by duttarnab** [GluuFederation/flex#2]
1. Go to Admin --> Active Users menu.
2. Date range showing undefined.
3. On clicking, it shows `?`.

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/152430199-4ed1b4b0-bcb1-4c03-827e-c29be6485a76.png)

![image](https://user-images.githubusercontent.com/7513418/152430325-f5b9f15a-4792-4fbe-9032-c997f70c54f3.png)
