### ISSUE TITLE
fix (admin-ui): issues oidc client page

### ISSUE THREAD

**Issue by duttarnab** [GluuFederation/flex#205]
Following 2 issues reported in admin-ui 
1. On the OIDC client list page `Client Name` column is blank.
2. OIDC client edit is not working.

**Comment by duttarnab** [comment]
Done

**Comment by mjatin-dev** [comment]
Reopen this issue because After edit OCID client we see blank page.

**Comment by mjatin-dev** [comment]
Closing issue after fix and check.
