### ISSUE TITLE
feat(admin-ui): added support for pure java scripts

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/flex#242]
### Description

AS now support pure Java scripts https://github.com/JanssenProject/jans/issues/318

UI must :
- allow to select programming language: `Jython`, `Java`.
- highlight java syntax (if Java is selected)  or python syntax if Jython is selected

config-api already supports CRUD for custom scripts. 

https://github.com/JanssenProject/jans/blob/5da6e2743761cbdf8f06b3dca9a5cf7c8af1abe3/jans-core/script/src/main/java/io/jans/model/custom/script/model/CustomScript.java#L61

Sample pure Java script can be found in docs:
https://github.com/JanssenProject/jans/wiki/Interception-scripts--(or--Custom-scripts)#using-pure-java-scripts

**Comment by duttarnab** [comment]
Done
