### ISSUE TITLE
feat(admin-ui): create SVG file wave image for new Admin UI sidebar

### ISSUE THREAD

**Issue by harryandriyan** [GluuFederation/flex#273]
-------------------

### Description

Create SVG file wave image for the new Admin UI sidebar

![wave](https://user-images.githubusercontent.com/7929947/176652163-0a30b0e0-685f-4782-b6a9-d45fb7dbbfe3.png)

**Comment by moabu** [comment]
@harryandriyan attached are the svgs.
![LightBlue](https://user-images.githubusercontent.com/47318409/176665763-3360cfd5-d13e-40de-ad7b-6dbf7a4f08d5.svg)
![LightGreen](https://user-images.githubusercontent.com/47318409/176665765-edb0c1dc-434b-48b1-af0b-382b1aa9cb67.svg)
![DarkBlue](https://user-images.githubusercontent.com/47318409/176665766-2b6e32ad-1c75-4dcc-b8f5-edc61e4d1c95.svg)

**Comment by harryandriyan** [comment]
Okay, thanks @moabu the SVG image now implemented, currently in the https://github.com/GluuFederation/flex/pull/265
