### ISSUE TITLE
BUG: Remove extraneous fields for spontaneous scopes

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/flex#279]
![image](https://user-images.githubusercontent.com/3717101/177395106-a1d3fc8b-8933-47f3-b71a-dc4fadd1bf42.png)

1. What are "OXAttributes" -- I don't even know. But furthermore, I thought OX was not-used branding from Gluu 4...
2. If there are two attributes specific to spontaneous scopes, why are these input fields taking up valuable real estate, but have no application for any scopes other than spontaneous?

**Comment by duttarnab** [comment]
fixed
