### ISSUE TITLE
fix (admin-ui) : page refresh issue

### ISSUE THREAD

**Issue by duttarnab** [GluuFederation/flex#281]
Steps:

1. Log in to admin-ui (deployed on apache server).
2. Click on Attributes --> All Attributes.
3. Refresh the page.
4. The browser shows 404 error

https://user-images.githubusercontent.com/32794267/115984541-31f1c280-a5c5-11eb-90d6-c9d562222c11.png

**Comment by duttarnab** [comment]
To fix this change add below Directory tag to `/etc/apache2/sites-available/https_jans.conf`.

```
<Directory "/var/www/html/admin">
    Options FollowSymLinks Indexes
        DirectoryIndex index.html
        AllowOverride All
        Order allow,deny
        Allow from all
        Options -MultiViews
        RewriteEngine On
        RewriteBase /admin
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteRule ^ index.html [QSA,L]
</Directory>
```

**Comment by devrimyatar** [comment]
Fixed
