### ISSUE TITLE
feat: (casa): Flex installer should be able to install casa alone

### ISSUE THREAD

**Issue by maduvena** [GluuFederation/flex#282]
Flex installer should allow installation of casa alone.
The flow can be as follows
A. During install : 
1) Install admin-ui [Y/n]?
2) Install casa [Y/n]?

B. After install
Admin UI and Casa should be installable using a post-install script

**Comment by maduvena** [comment]
Can we add the following commands too? 
1. python3 flex_setup.py -remove casa 
2. python3 flex_setup.py -remove admin-ui

**Comment by moabu** [comment]
I think we can close this issue
