### ISSUE TITLE
How to make Gluu expose Prometheus metrics with Helm?

### ISSUE THREAD

**Issue by ghuber-aarete** [GluuFederation/flex#287]
**Describe the bug**
How to make Gluu expose Prometheus metrics?

**To Reproduce**
Assuming I'm using this chart
https://artifacthub.io/packages/helm/gluu-flex/gluu
and install `auth-server`, `config-api`, and `scim` components... how to make them expose the metrics endpoint like i.e. here
https://gluu.org/docs/gg/plugin/gluu-metrics/
?

**Expected behavior**
Gluu exposes metrics endpoint

**Comment by moabu** [comment]
https://github.com/GluuFederation/flex/blob/main/flex-cn-setup/pygluu/kubernetes/templates/helm/gluu/values.yaml#L827 for the prometheus jmx. However we are still working on adding metrics and telemetry in general. The only available metric is the monthly active user metric currently. 

Example:

1. created a new client with the below  details. I didn't change any settings beside whats in the Standard settings:

OPENID CONNECT CLIENTS DETAILS
------------------------------
- **Name:** test
- **Client ID:** 9cc66d49-31f1-4a12-b1c2-c38f77417b40
- **Subject Type:** pairwise
- **ClientSecret:** XXXXXXXXXXX
- **Application Type:** web
- **Persist Client Authorizations:** true
- **Pre-Authorization:** false
- **Authentication method for the Token Endpoint:** client_secret_basic
- **Logout Session Required:** false
- **Include Claims In Id Token:** false
- **Disabled:** false
- **Scopes:** [openid]
- **Grant types:** [client_credentials]
- **Response types:** [token]


2. 
```
curl -k https://test.gluu.org/oxauth/restv1/internal/stat?month=202106 -u "9cc66d49-31f1-4a12-b1c2-c38f77417b40:2E585aiKkE26xmZXDXJdiI9qhTvqtKfeUXKac4z6"
{"response":{"202106":{"monthly_active_users":0,"token_count_per_granttype":{}}}}
```
You can also specify the open metrics format in the call 

```
curl -k https://test.gluu.org/oxauth/restv1/internal/stat?month=202106&format=openmetric -u "9cc66d49-31f1-4a12-b1c2-c38f77417b40:2E585aiKkE26xmZXDXJdiI9qhTvqtKfeUXKac4z6"
```
