### ISSUE TITLE
feat (admin-ui) : fix labels of oidc  form field

### ISSUE THREAD

**Issue by duttarnab** [GluuFederation/flex#298]
1. `TLS` is an acronym, and therefore all caps
![image](https://user-images.githubusercontent.com/32794267/178507363-8b9e6a1e-6625-4ff7-bf90-ae77057c2eac.png)

2. Access Token is two words
![image](https://user-images.githubusercontent.com/32794267/178507732-9e4848d9-1927-4f7b-a9ee-8a8c58644282.png)

3. the correct way to write id_token is with an underscore, all lowercase.

![image](https://user-images.githubusercontent.com/32794267/178508398-bb8e602d-9450-40d2-b2ca-2b46ca211a8a.png)

**Comment by nynymike** [comment]
Replaced by https://github.com/GluuFederation/flex/issues/301

**Comment by nynymike** [comment]
Replaced with https://github.com/GluuFederation/flex/issues/301
