### ISSUE TITLE
fix (admin-ui) : only single default ACR could be assigned to an oidc client

### ISSUE THREAD

**Issue by duttarnab** [GluuFederation/flex#300]
Currently, in oidc form, multiple acr values could be assigned to client. We should be able to assign only single ACR to oidc client.

![image](https://user-images.githubusercontent.com/32794267/178514251-89cfb265-3354-4103-803d-480a6e84afad.png)

**Comment by nynymike** [comment]
Duplicate now of https://github.com/GluuFederation/flex/issues/301
