### ISSUE TITLE
Bug (admin-ui) Client Form: [object Object] value is present

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/flex#304]
Why is `[object Object]` populating the edit client form? Also, what is that `0` doing there? 

![image](https://user-images.githubusercontent.com/3717101/178836737-ca1bb6f1-e3fa-4f7b-b862-54441fd8fcb0.png)

![image](https://user-images.githubusercontent.com/3717101/178836777-723844df-6896-4b9e-b3f4-40caf17ba4dc.png)

Also in the Auth Server Properties:

<img width="945" alt="image" src="https://user-images.githubusercontent.com/3717101/178859302-f5639364-93eb-4af6-8d99-3a1f6066bb9e.png">

**Comment by duttarnab** [comment]
We have raised the following issue for config-api team to fix this issue: 

https://github.com/JanssenProject/jans/issues/1765

**Comment by duttarnab** [comment]
Fixed
