### ISSUE TITLE
Bug: admin-ui: Scopes Form is broken -- missing most important field (id) 

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/flex#305]
Currently, you cannot add a scope because the form is missing the most important field--the jansID, which is the scope value the client developer requests at the `/token` endpoint.  

For some reason, three random pieces of information are in a box called `oxAttributes` -- note: the `ox` prefix is not supposed to be carried forward into Jans.

See the screenshots below of the TUI for an idea of how this form should behave.

![jans_admin-scopes-1 drawio](https://user-images.githubusercontent.com/3717101/178849955-5a4d5210-818a-4470-b3b3-13cd9fc404f8.png)
![jans_admin-scopes-2 drawio](https://user-images.githubusercontent.com/3717101/178849959-d9fc7baf-e09e-4b16-8078-6fce2575b3e6.png)
![jans_admin-scopes-3 drawio](https://user-images.githubusercontent.com/3717101/178849962-8bb57b5c-eb8a-4dbc-89d7-0e2a7af9977e.png)
![jans_admin-scopes-4 drawio](https://user-images.githubusercontent.com/3717101/178849965-5249b2ac-9cce-458b-8a6e-189f10eb63cd.png)

**Comment by duttarnab** [comment]
done
