### ISSUE TITLE
feat (Admin UI): Add description to keys

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/flex#306]
This view is not particularly helpful: 
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/3717101/178858406-53cc3598-d12e-4610-b0e9-8d3b04de2e8c.png">

Next to the `+` we should add the description. Right now, there are no descriptions, but there is a [Jans Issue](https://github.com/JanssenProject/jans/issues/1790) to put something meaningful there.

**Comment by duttarnab** [comment]
The issue is fixed after reinstallation of jans-server.

![image](https://user-images.githubusercontent.com/32794267/179216446-a24cc4db-3c45-40a4-95b3-2a1e3c93d838.png)

**Comment by duttarnab** [comment]
I found that 2 days after reinstallation the keys `name` and `desc` are missing from jwks_url response. Immediate after reinstallation `name` and `desc` were present.  
https://admin-ui-test.gluu.org/jans-auth/restv1/jwks

![image](https://user-images.githubusercontent.com/32794267/179449195-5b403cd4-02f1-40c3-8ab8-85b9a5bdfe0d.png)

**Comment by duttarnab** [comment]
fixed
