### ISSUE TITLE
feat: Remove Auth Server Defaults page

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/flex#307]
* As Logging has moved to its own page, this logging panel should be removed
* As the only thing left on this page is "Default Authentication Method (ACR)"... this might as well be moved to the "Properties" page. It does not need to be in its own section. Also "ACR" is an acronym and should be capitalized. 

<img width="1344" alt="image" src="https://user-images.githubusercontent.com/3717101/178858659-1a941df4-be48-4b29-a76d-0d5591beffc4.png">

**Comment by duttarnab** [comment]
done
