### ISSUE TITLE
feat (Admin UI): Session Viewer

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/flex#331]
We need a way to view sessions... this should be READ ONLY, not update.

**Comment by duttarnab** [comment]
We are thinking of creating a session report with the following details

| sid | username | ip_address | client_id used | Authn Time | session exp |
|---- | ----------- | ------------|----------------|---------------|-------------|
|e8938acb-e68e-4044-92c7-057d9e233fa4|admin|202.8.117.170|2000.42ab3b6f-52fd-4815-8407-be69b10722c9|2022-08-08T07:54:24.293Z|

**Comment by duttarnab** [comment]
Hi @yuriyz 
![image](https://user-images.githubusercontent.com/32794267/183906189-5f7fa55b-9bb2-4572-b117-530a738da188.png)
We need a feature here to revoke all sessions by user. I think the below auth-server endpoint can do this. Could you please confirm.

https://github.com/JanssenProject/jans/blob/main/jans-auth-server/server/src/main/java/io/jans/as/server/revoke/RevokeSessionRestWebService.java#L68
