### ISSUE TITLE
feat (Admin UI): OAuth Token Viewer

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/flex#332]
Admins should be able to view OAuth tokens that currently exist in either the database or cache: access tokens, refresh tokens, id_tokens, userinfo tokens (if they are ever persisted). These should like to the client they were issued to, and potentially a person (if there is a person associated with the token).

**Comment by duttarnab** [comment]
We are thinking to create token report with following information.
|Token Code| Token Type|Grant Type| User Id | User Dn | Client Id|Scope|
|-------------|-------------|------------|---------|----------|----------|-------|
|9c72afffe6b38802faf225f44b17b3282bbfc5f169370481396bcc4610405c8b|access_token|authorization_code|admin|inum=a282d79f-4bc9-441c-8760-a09ab523fdb1,ou=people,o=jans|2000.42ab3b6f-52fd-4815-8407-be69b10722c9|openid profile email|

**Comment by duttarnab** [comment]
Hi @yuriyz 

We are thinking to show a token report with the above-mentioned columns.  There will be a revoke button before each token record which will delete the token record from the database.  Please advise if this is the proper way to revoke token.


![image](https://user-images.githubusercontent.com/32794267/184182091-8525d26e-f090-4b75-a339-3f86906cc442.png)

**Comment by yuriyz** [comment]
Direct remove is hacky because AS does not know about it. Please use `/revoke` token AS endpoint. 

https://github.com/JanssenProject/jans/blob/6c1caa1c4c92d28571f8589cd701e6885d4d85ef/jans-auth-server/server/src/main/java/io/jans/as/server/revoke/RevokeRestWebServiceImpl.java#L81

**Comment by duttarnab** [comment]
@yuriyz , we will list all token records on the report from the database. And admin is allowed revoke any OAuth tokens.

But we do not save the actual token in the database. (We are saving token-code and other details.) And I think `/revoke` needs actual token in request parameter. So I was thinking how to use `/revoke` endpoint.

**Comment by yuriyz** [comment]
I see, yeah, AS will not allow to drop any token as well as actual token code has to be provided. OK, let it be, add endpoint to jans-config-api which will make direct remove from persistence.
