### ISSUE TITLE
bug (admin-ui) : testing ldap always shows `test failed` the first time

### ISSUE THREAD

**Issue by duttarnab** [GluuFederation/flex#373]
**To Reproduce**
1. Go to 'Services --> Persistence --> Ldap' 
2. Expand the record and then Click on `Test Connection`. 
3. It will always show `test failed` the first time. The response from api is `true` which means connection is successful.

![image](https://user-images.githubusercontent.com/32794267/185389081-dd1ca2fe-aecc-42da-8a4c-7e290e342565.png)

**Comment by harryandriyan** [comment]
accidentally closed the issue
