### ISSUE TITLE
feat (admin-ui) : improvement required in oidc client info in view mode

### ISSUE THREAD

**Issue by duttarnab** [GluuFederation/flex#375]
Following improvements are required in oidc clients view pages

1. User should be able to select and copy the field values 
2. There are some links in oidc client forms to view uma resources, spontaneous scopes. User should able to open those links in view mode

**Comment by syntrydy** [comment]
@duttarnab i guess the view concerned here is the OIDC Clients Details under Auth server plugin, right?

**Comment by duttarnab** [comment]
yes, correct.

![image](https://user-images.githubusercontent.com/32794267/185905656-a07126e2-0f61-4385-93a4-424241bf99a8.png)

**Comment by syntrydy** [comment]
okay

**Comment by duttarnab** [comment]
done
