### ISSUE TITLE
feat (admin-ui) : need to add `claims  gathering script` field in `CIBA/PAR/UMA` tab of oidc client 

### ISSUE THREAD

**Issue by duttarnab** [GluuFederation/flex#376]
Please add `claims  gathering script` field in `CIBA/PAR/UMA` tab of oidc client (as shown in figure).
![image](https://user-images.githubusercontent.com/32794267/185597689-8564aeb8-aa52-4123-9a19-a3653a2701c4.png)

Claims gathering scripts can be found here

![image](https://user-images.githubusercontent.com/32794267/185599393-9b851305-07ae-42b1-9b50-3171b852c7ba.png)

**Comment by mjatin-dev** [comment]
@duttarnab , what should be the key to send this field in payload ?

**Comment by mjatin-dev** [comment]
Closing issue as this field is not available.
