### ISSUE TITLE
feat (admin-ui) : use provided tooltip for fields in oidc clients form

### ISSUE THREAD

**Issue by duttarnab** [GluuFederation/flex#378]
**Please below tooltips for fields in oidc clients form.**

**Tab: Basic**
- inum- The OpenID Connect unique client identifier. It MUST NOT be currently valid for any other registered Client.
- Client name - Name of the Client to be presented to the End-User.
- Client secret - Client Secret. The same Client Secret value MUST NOT be assigned to multiple Clients. This value is used by Confidential Clients to authenticate to the Token Endpoint and for the derivation of symmetric encryption key values. It is not needed for Clients selecting a token_endpoint_auth_method of private_key_jwt unless symmetric encryption will be used.
- Authn method token endpoint - Requested Client Authentication method for the Token Endpoint.
- Subject type - `subject_type` requested for responses to this Client. The `subject_types_supported` Discovery parameter contains a list of the supported `subject_type` values for this server.
- Sector Identifier URI - URL using the https scheme to be used in calculating Pseudonymous Identifiers by the OP.
- Grants - List of the OAuth 2.0 Grant Types that the Client is declaring that it will restrict itself to using. 
- Response types - List of the OAuth 2.0 response_types that the Client is declaring that it will restrict itself to using. 
- Supress authorization - OAuth 2.0 allows providers to prompt users for consent before releasing their personal information to a client (application). The standard consent process is binary: approve or deny. The selection of this field will not prompt the users for consent.
- Application type - Kind of the application.
- Redirect URIs - List of Redirection URI values used by the Client. One of these registered Redirection URI values must exactly match the redirect_uri parameter value used in each Authorization Request.
- Redirect Regex - If this field is set then redirectUri must match to this regexp.

**Tab: Tokens**
- Access token type - Specifies the type of Access token generated using the client.
- Include claims in id_token - If selected then claims are included in id_token.
- Add auth_time to id_token - If selected the auth_time claim is included in id_token.
- Run Introspection Script Before AccessToken As Jwt Creation And Include Claims - If this field is set to true then AS with run introspection script before Access token (as JWT) creation and include claims.

**Tab: Logout**
- Front channel. logout URI - Relying Party (RP) URL that will cause the RP to log itself out when rendered in an iframe by the OP. This is used in the front-channel logout mechanisms, which communicate logout requests from the OP to RPs via the User Agent.
- Back channel. logout URI - Relying Party (RP) URL that will cause the RP to log itself out when sent a Logout Token by the OP. This is used in the back-channel logout mechanisms, which communicate logout requests directly between the OP and RPs.
- Back channel. logout session required - Boolean value specifying whether the RP requires that a sid (session ID) Claim be included in the Logout Token to identify the RP session with the OP when the backchannel_logout_uri is used.
- Front channel. logout session required: - Boolean value specifying whether the RP requires that iss (issuer) and sid (session ID) query parameters be included to identify the RP session with the OP when the frontchannel_logout_uri is used.
**Tab: Software Info**
- Software id - Specifies a unique identifier string (UUID) assigned by the client developer or software publisher used by registration endpoints to identify the client software to be dynamically registered.

**Tab: CIBA / PAR / UMA**
CIBA
- Token delivery method - Specifies how backchannel token wiil be delivered.
PAR
- Require lifetime - Represents the lifetime of Pushed Authorisation Request (PAR).
- requirePar - Is Pushed Authorisation Request (PAR) required?
UMA
- RPT token type - Specifies whether RPT should be return as signed JWT.
- Claims redirect URI - Array of The Claims Redirect URIs to which the client wishes the authorization server to direct the requesting party's user agent after completing its interaction.
- RPT Modification Script - List of Requesting Party Token (RPT) claims scripts.

**Tab: Encription / Signing**
JARM
- JWS alg for signing - JWS alg algorithm JWA required for signing authorization responses.
- JWS alg for encryption - JWE alg algorithm JWA required for encrypting authorization responses.
- JWS enc for encryption - JWE enc algorithm JWA required for encrypting auhtorization responses.

**Tab: Advanced Client Properties**
- Allow spontaneous scopes - Whether to allow spontaneous scopes for the client.
- Spontaneous scope validation regex - List of spontaneous scope regular expression.
- Spontaneous scopes - Spontaneous scopes created using client.
- Default prompt=login - If enabled then sets prompt=login to the authorization request, which causes the authorization server to force the user to sign in again before it will show the authorization prompt.
- TLS Subject DN -  String representation of the expected subject distinguished name of the certificate, which the OAuth client will use in mutual TLS authentication.

**Tab: Client Scripts**
- Spontaneous Scopes - List of spontaneous scope scripts.
- Update Token - List of update token scripts.
- Post Authn - List of post authentication scripts.
- Introspection - List of introspection scripts.
- Password Grant -  List of Resource Owner Password Credentials (ROPC) scripts.
- OAuth Consent - List of consent gathering scripts.

**Comment by mjatin-dev** [comment]
Merged
