### ISSUE TITLE
fix (admin) : admin ui should remember the language and theme selection by the user every time after login

### ISSUE THREAD

**Issue by duttarnab** [GluuFederation/flex#379]
Steps: 

1. Log in to admin-ui.
2. Select a different theme and language
3. Log out
4. Re-login
5. The admin-ui again shows default theme and language

Expected:

The admin-ui should remember the theme and language selected last time by user and should set it everytime the user logs in.

**Comment by duttarnab** [comment]
I think we also need API to store language/theme by the user in configuration. This will help to persist the information even if the browser cache is cleared.

**Comment by syntrydy** [comment]
@duttarnab i think we can avoid this. Most users don't clear the cache. Do we really want to store that in the database for each user?

**Comment by duttarnab** [comment]
@syntrydy hmm.. I agree. In that case @harryandriyan please store theme/lang details by user.

**Comment by duttarnab** [comment]
Done
