### ISSUE TITLE
feat (admin-ui) : implement server side pagination in person attributes

### ISSUE THREAD

**Issue by duttarnab** [GluuFederation/flex#418]
Now parameters are added in `/jans-config-api/api/v1/attributes` so that we can implement server-side pagination admin-ui on search page.

**Page:** Schema --> Person

**Request parameters:** 
- `limit` - number of records in each page.
- `startIndex` - the page number to show
- `pattern` - the pattern to be searched. Useful in searching

**Response parameters**
- `data` - list of records
- `totalItems` - toatal number of records in database

**Comment by mjatin-dev** [comment]
Merged
