### ISSUE TITLE
fix (admin-ui) : in json configuration screen `Authorization Request Custom Allowed Parameters` shows `object` as value

### ISSUE THREAD

**Issue by duttarnab** [GluuFederation/flex#428]
![image](https://user-images.githubusercontent.com/32794267/189286564-b0158c37-c295-4102-83c2-d19c625cc1a6.png)

**Comment by syntrydy** [comment]
The data sent from the backend is a string  ("[object Object]") reason why we get the data as it is.

`  "clientWhiteList": [
    "*"
  ],
  "clientBlackList": [
    "*.attacker.com/*"
  ],
  "legacyIdTokenClaims": false,
  "customHeadersWithAuthorizationResponse": true,
  "frontChannelLogoutSessionSupported": true,
"authorizationRequestCustomAllowedParameters": [
    "[object Object]",
    "[object Object]",
    "[object Object]",
    "[object Object]",
    "[object Object]"
  ],
  "loggingLevel": "INFO",
  "loggingLayout": "text",
  "updateUserLastLogonTime": false,
  "updateClientAccessTime": false,
  "logClientIdOnClientAuthentication": true,
  "logClientNameOnClientAuthentication": false,
  "disableJdkLogger": true,`

**Comment by duttarnab** [comment]
Fixed
