### ISSUE TITLE
feat (admin-ui): show active users page on dashboard

### ISSUE THREAD

**Issue by duttarnab** [GluuFederation/flex#43]
The current information on the dashboard is not very useful like pie charts on OpenID Clients, Custom scripts etc.

We need to show the Active Users page on the dashboard and remove its Menu from `Admin` plugin.

![image](https://user-images.githubusercontent.com/32794267/152928777-411fa4e4-0a5a-45ea-947b-35a3c6f61d31.png)

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/153875332-104081a2-e0d3-4183-a336-8074ef8f1a09.png)

![image](https://user-images.githubusercontent.com/7513418/153875456-f26b8f60-40e0-465d-aee9-77d3f1309247.png)

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/154998170-e4856860-c22a-4fc5-8aa8-fab4e08eaf85.png)

**Comment by duttarnab** [comment]
Done
