### ISSUE TITLE
feat (admin-ui): Add search component to scripts page under Admin

### ISSUE THREAD

**Issue by syntrydy** [GluuFederation/flex#436]
Currently, it's not possible to search for scripts on the script page.

![Screenshot from 2022-09-14 12-02-16](https://user-images.githubusercontent.com/7513418/190137458-b8d68143-2e37-432b-8502-257e95b652d5.png)

**Comment by syntrydy** [comment]
![sc3](https://user-images.githubusercontent.com/7513418/190365532-daa74a59-8e48-4992-b32e-0672a21d47cd.png)

**Comment by duttarnab** [comment]
done
