### ISSUE TITLE
feat (admin-ui): Fix [object Object] on client basic and software panel

### ISSUE THREAD

**Issue by syntrydy** [GluuFederation/flex#437]
We still have [object Object] for some fields, we can display the values themselves or an empty string ('') if the values are not present instead of keeping [object Object].

![image](https://user-images.githubusercontent.com/7513418/190159768-2e3c38f5-3633-4fed-ad6a-7172125bbc7f.png)

**Comment by syntrydy** [comment]
In the screenshots below, the changes can be seen.

![sc1](https://user-images.githubusercontent.com/7513418/190364248-0711c102-cb2a-4970-9b05-282859682ddb.png)

![sc2](https://user-images.githubusercontent.com/7513418/190364267-6926a769-8955-478e-aafc-87ce544b93ce.png)

**Comment by duttarnab** [comment]
Fixed
