### ISSUE TITLE
FEAT: Send MAU to LicenseSpring when UI starts

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/flex#439]
LicenseSpring supports custom attributes. Could we send MAU data from the last 12 months to License Spring each time the AdminUI starts? This way we could re-invoice without asking the customer to generate a report.

**Comment by duttarnab** [comment]
> Could we send MAU data from the last 12 months to License Spring each time the AdminUI starts? 

yes, this is possible using licenseSpring `/product-custom-fields` APIs.

After login into admin-UI, the application will check if the MAU data of the current month is present on licenseSpring server. If it is not present then the application will make an entry using  `/product-custom-fields` APIs.

The entries of mau data will be in the following format - 

**key**: mau_yyyymm
**value**: <integer_value_of_current_month_mau>

**Comment by duttarnab** [comment]
The custom attribute is a key-value pair. With the current subscription plan, we are allowed to create not more than 3 attributes.

So after considering the above point, we will have the following two custom attributes on the licenseSpring server.
|--|--|
|Key|Value|Format|
|`current_yyyy_mm`|2022_11|yyyy_mm|
|`last_twelve_months_mau`| JAN_100_FEB_101_MAR_102_APR_101_MAY_101_JUN_102_JUL_103_AUG_100_SEP_101_OCT_101_NOV_100_DEC_0|

**Comment by duttarnab** [comment]
The license flow has been changed. See `https://github.com/GluuFederation/flex/issues/1148`. Closing this issue due to changes in requirement.
