### ISSUE TITLE
feat (admin-ui): Fix bug on client details dropdown

### ISSUE THREAD

**Issue by syntrydy** [GluuFederation/flex#440]
View

![scr1](https://user-images.githubusercontent.com/7513418/190372861-88f1126a-4d76-4f7e-bb73-70f44164e54e.png)

When the drop-down is clicked to view the client details we get an error as shown below

![scr2](https://user-images.githubusercontent.com/7513418/190372908-ceaed3da-61cd-49b7-aa09-327652b7099b.png)

**Comment by syntrydy** [comment]
Fix
![scr3](https://user-images.githubusercontent.com/7513418/190393403-27086ed3-17ad-42b6-8f9a-4240bd3f3094.png)

**Comment by duttarnab** [comment]
done
