### ISSUE TITLE
feat: add options to setup.properties

### ISSUE THREAD

**Issue by devrimyatar** [GluuFederation/flex#459]
**Is your feature request related to a problem? Please describe.**
By default, flex-linux-setup installs casa and admin-ui, additionally add options `installCasa` and `installAdminUi` to setup.properties

Also add options:
```
adminui-authentication-mode=casa
adminui-authentication-mode=casa
gluu-scan-cert=True
enable-script=5018-D4BF 8BAF-80D6 8BAF-80D7 92F0-BF9E
```
**Describe the solution you'd like**
flex-setup should read setup.properties to decide if those components are to be installed.

**Comment by moabu** [comment]
yes we should keep the default to install both but then override if these options are available.

**Comment by devrimyatar** [comment]
Also add these options:
```
  ox-trust-authentication-mode=casa
  ox-authentication-mode=casa
  gluu-scan-cert=True
  enable-script=5018-D4BF 8BAF-80D6 8BAF-80D7 92F0-BF9E
```
