### ISSUE TITLE
feat: Need option in setup.py to download all required packages without setup

### ISSUE THREAD

**Issue by nikdavnik** [GluuFederation/flex#464]
In order to build binary packages for flex we need to have option in setup script to download all necessary components without setup and run setup part after binary package is installed on system.

**Comment by devrimyatar** [comment]
@moabu Will the flex package contain whole jans + flex? Or just flex componentes?

**Comment by moabu** [comment]
it will contain both jans and flex components. Otherwise it will need jans package + flex package to work together and in order and I think that will be a little heavy on the end user
