### ISSUE TITLE
Admin UI License Registration

### ISSUE THREAD

**Issue by Cookedjc** [GluuFederation/flex#497]
Problem:

Today you need to enter fixed values into the License Screen for the Flex UI including:
licenseSpring.apiKey=
licenseSpring.productCode=
licenseSpring.sharedKey=
licenseSpring.managementKey=

And then on a second screen:
license-key 

Ideally, the first four values would be obtained from a Gluu API, as these are Gluu credentials.

**Comment by duttarnab** [comment]
> licenseSpring.apiKey=9816ef29-a5fa-4df7-bba7-b7ae83711d28
> licenseSpring.productCode=`001
> licenseSpring.sharedKey=FW4xYR1nFnY6ISWulhMOYSBqx1Li_10D74RznCZxVtQ
> licenseSpring.managementKey=raGfAOAy.y9oyJYZaBb8rlM4yfTbNUB7l8InWdE2l

The following information will be common for all users as these are related to the `admin-ui` product created on license-spring.

> All except the License is unique to a user / entity.
> license-key

`license-key` will be unique for each user. There is a field called `Maximum Activation` associated with each license-key. If  `Maximum Activation` is set to `1` then the `license-key` will not be valid for another activation. It means another user cannot use the same `license-key` if it has been already activated by the client.

**Comment by duttarnab** [comment]
Currently, users need to enter the` API key, shared key, product code and license-key` in admin-ui for license activation. We need to hide the ` API key, shared key, product code` from the user.  The user should be able to activate the license using `license-key`.

**The Solution**
1. Every time before calling the `licenseSpring` APIs, Admin UI backend (config-API plugin) will call the following endpoints of `Gluu's Internal Rest Application`.
- /licenseSpring/credentials (to get signed and encrypted `API key, shared key, product code`)
- /licenseSpring/credentials/keys (to get keys to decrypt and verify credentials)
2. We will configure allowed hostnames in `Gluu's Internal Rest Application`. The requests from the configured hostnames will be only allowed to `Gluu's Internal Rest Application`

![Clipboard - December 23, 2022 9_35 PM](https://user-images.githubusercontent.com/32794267/209437094-50391a92-1018-4e45-a29f-fe8d28986391.png)

**Comment by duttarnab** [comment]
Admin-UI team will make FE+BE changes once APIs are ready.

**Comment by duttarnab** [comment]
Here are the steps to be implemented in admin-ui for getting license credentials from SCAN. 

1. During Flex installation if the user chooses to install admin-ui then it will ask to enter SSA (obtained from SCAN) for license APIs access.
2. The User will enter SSA which is presented to the Authorization Server (AS) for DCR and will get client credentials as the response. The client credentials will be saved in Jans server persistence (ldap/mysql) in admin-ui configuration.
3. To access SCAN license APIs (/license/credentials and /license/credentials/keys) Admin UI will use the client credentials to generate the token containing license scopes.
4. Using obtained token in the authorization header admin-ui will request /license/credentials and /license/credentials/keys

**Comment by nynymike** [comment]
You want the user to just paste in the JWT? Perhaps it can be given as a file when you run setup, for example `--ssa`  ?

**Comment by duttarnab** [comment]
> You want the user to just paste in the JWT? Perhaps it can be given as a file when you run the setup, for example --ssa ?

ok noted. Reading SSA jwt (during flex installation) and DCR (i.e. #1 and #2) will be the work of the flex installation script. So @devrimyatar  can advise if the installation script can accept the SSA file during installation.

**Comment by duttarnab** [comment]
Hi @devrimyatar 
1. During Flex installation if the deployer chooses to install admin-ui then, the setup will ask to enter SSA for license API access. the SSA generated will have `https://jans.io/oauth/jans-auth-server/config/adminui/license.read` scope.
2. setup.py will present the SSA to https://accounts.gluu.org/ (the SCAN Auth Server) during DCR to obtain client credentials. Setup will save the client credentials in the admin-ui configuration (under `jansConfApp` field).

```
{"oidcConfig":{"authServerClient":{.....},"tokenServerClient":{.....}}, **"licenseClientCredential":{"client_id": "xxxxxxx.xxxxxxxx.xxxxxxxxx", "client_secret": "xxxxxxxx.xxxxxxxxxxx.xxxxxxxxxxx"}**}
```

**Comment by duttarnab** [comment]
[license_api_spec.txt](https://github.com/GluuFederation/flex/files/10756001/license_api_spec.txt)

@soheil-star01, as discussed please find the license APIs specs attached.

**Comment by devrimyatar** [comment]
@duttarnab Please create a seperate issue for flex_linux_setup

**Comment by duttarnab** [comment]
> @duttarnab Please create a seperate issue for flex_linux_setup
@devrimyatar  https://github.com/GluuFederation/flex/issues/766

**Comment by duttarnab** [comment]
Hi @mjatin-dev 

We need to do the following changes to UI 👍 

1.  When a user fires admin-ui URL, the following screen to collect `api-key`, `shared-key` and `product-code` will not be shown.      
![image](https://user-images.githubusercontent.com/32794267/221548820-e5b4cf71-b5b6-4906-809f-f857bab7921e.png)

2. Admin UI will first check if license has been activated for the application using the below endpoint.

`GET` `/admin-ui/license/isActive`

**Response:** 

```
{
  "apiResult": true,
  "responseMessage": "Valid license present.",
  "responseCode": 200
}
```

3. If `responseCode` is `200` and `apiResult` is `true` then it will redirect to login page.
4. If  `apiResult` is `false` in response then it will show the screen to get `license-key` (created before).
5. On entering license-key and clicking of submit button, it will call the below endpoint to activate license-key.
`POST` `/admin-ui/license/activateLicense`
**Request-body**
```
{
  "licenseKey": "string"
}
```

6. On getting a response with `"apiResult": true`, it will redirect to the login page.
7. If `apiResult` in response is `false` then it will display the message that `The entered license-key is not valid.`

**Comment by duttarnab** [comment]
done

**Comment by duttarnab** [comment]
Done
