### ISSUE TITLE
fix(admin-ui): hindrance on client scope assignment

### ISSUE THREAD

**Issue by moabu** [GluuFederation/flex#502]
In the latest version of the AdminUI deployed with 1.0.3 Jan's and MySQL as the backend db, it is not possible to properly assign scopes for a client:

- newly created scopes don't show up in the drop-down list of scopes to pick
- when updating the scopes of a client and attempting to persist it, following error is returned by the server: 
```
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.lang.String` from Object value (token `JsonToken.START_OBJECT`) at [Source: (org.eclipse.jetty.server.HttpInput); line: 1, column: 168] (through reference chain: io.jans.as.common.model.registration.Client["clientName"])
```

**Comment by duttarnab** [comment]
> newly created scopes don't show up in the drop-down list of scopes to pick

We will fix this issue

> when updating the scopes of a client and attempting to persist it, the following error is returned by the server:

We are waiting for the fix of the below issues to resolve this problem.
https://github.com/JanssenProject/jans/issues/1765
https://github.com/JanssenProject/jans/issues/1482

**Comment by mjatin-dev** [comment]
**newly created scopes don't show up in the drop-down list of scopes to pick**
-- This issue is because of the limit to get API records as we have implemented server side pagination now so it will fetch only 50 records.
-- (Temporary fix) Fixed this issue for now by setting limit to 100 in the API call.

-- (Permanent Fix) we need to make API cable to search multiple items (and need to implement server side search in the existing field)

**Comment by duttarnab** [comment]
> newly created scopes don't show up in the drop-down list of scopes to pick

> -- (Permanent Fix) we need to make API cable to search multiple items (and need to implement server side search in the existing field)

we have implemented the fix in config-api and admin-ui

**Comment by duttarnab** [comment]
Hi @moabu we have tested today. We are able to assign newly created scopes to clients.
![image](https://user-images.githubusercontent.com/32794267/201854087-300afa78-3fea-48fb-8c0e-bcebcfe567cb.png)

**Comment by duttarnab** [comment]
> newly created scopes don't show up in the drop-down list of scopes to pick
Fixed
> when updating the scopes of a client and attempting to persist it, following error is returned by the server:
Fixed
