### ISSUE TITLE
fix (admin-ui) : logging details are not saving

### ISSUE THREAD

**Issue by duttarnab** [GluuFederation/flex#523]
Steps to reproduce: 

1. Save the changed logging details.
2. Go to another page then revisit the logging page.
3. The modified logging details are not saved.

![image](https://user-images.githubusercontent.com/32794267/196625105-cc11a213-e95b-4667-94bf-f27b5996b376.png)

**Comment by harryandriyan** [comment]
Issue solved by this PR, thanks!
https://github.com/GluuFederation/flex/pull/538
