### ISSUE TITLE
fix: difference in `delete` icon image  in config-api with other pages

### ISSUE THREAD

**Issue by duttarnab** [GluuFederation/flex#64]
**Describe the bug**
We should use the common image for delete icon in all pages.

**Screenshots**
![image](https://user-images.githubusercontent.com/32794267/153853130-f81f7824-e002-46a3-a07c-c153d900ec11.png)
![image](https://user-images.githubusercontent.com/32794267/153853416-c99686d8-d954-4549-9732-55feab404be7.png)

**Comment by mjatin-dev** [comment]
https://github.com/GluuFederation/flex/pull/97

**Comment by mjatin-dev** [comment]
fixed and checked on https://admin-ui-test.gluu.org/
