### ISSUE TITLE
fix: in the dashboard, the same `date` is shown multiple times on the x-axis

### ISSUE THREAD

**Issue by duttarnab** [GluuFederation/flex#65]
**Describe the bug**
1. In the dashboard, the same `date` is shown multiple times on the x-axis.
2. The heading of the dashboard is `Actives Users && Access Token Stats`. There should be some generic heading (like `Dashboard`) as we going to show many things on the dashboard. Here is the list.

> - successful versus failed authentication attempts
> - the total number of people in the database
> - The number of currently active sessions?
> - Total number of FIDO devices registered to users
> - SCIM usage information: Ideally, it would be nice to see the number of POST, PUT, GET, PATCH, DELETE operations 

**Screenshots**
![image](https://user-images.githubusercontent.com/32794267/153857263-090dac9b-0acb-4f15-95ed-6208653c55b1.png)

**Comment by syntrydy** [comment]
fixed
