### ISSUE TITLE
fix: issues in permission in config-api

### ISSUE THREAD

**Issue by duttarnab** [GluuFederation/flex#66]
**Describe the bug**
- **A row is moved to the last row of the table when a description is added to it. Ideally, it should at the same place**
1. Add description to the first row record
2. After save it is automatically moved to the last row of table.

- **The heading of the Permission page is `Config API Roles`. It should be `Config API Permissions`.**

![image](https://user-images.githubusercontent.com/32794267/153860213-5f3f6fe5-3703-49d6-b989-6e9da469e9f5.png)

- **No information appears when we expand a row.**
![image](https://user-images.githubusercontent.com/32794267/154404312-38860134-a10f-49a3-b213-503a8ee6008a.png)

**Comment by syntrydy** [comment]
I think i fixed this  while working on another task
