### ISSUE TITLE
fix(admin-ui) : Issues in multiple pages

### ISSUE THREAD

**Issue by mjatin-dev** [GluuFederation/flex#663]
- [x] 1. `client_name` is not visible
- [x] 2. Unable add a new ldap entry
- [x] 3. Getting following (success and error at same time) alert when trying to save a scope
- [x] 4. After saving a client it is showing Success alert without redirecting to client list page. The disadvantage is after saving if I change some field and save again then it a create new entry.
- [x] 5. While editing User , the page is allowed to save even if all fields are cleared. It should not allow to save if any of the field is removed
- [x] 6. While saving/modifying client, it should show alert if client is saved without entering any Redirect URIs. `Redirect URIs` is a mandatory field.
- [x] 7. In pagination the startIndex should start from 0. ref: https://github.com/JanssenProject/jans/issues/3296

**Comment by duttarnab** [comment]
7. In pagination the startIndex should start from 0. ref: https://github.com/JanssenProject/jans/issues/3296

**Comment by nynymike** [comment]
Please use checkboxes for multi-task issues and update on completion.

**Comment by mjatin-dev** [comment]
Fixed
