### ISSUE TITLE
feat(admin-ui): OpenID Client Form Need Finish Button on every page

### ISSUE THREAD

**Issue by mjatin-dev** [GluuFederation/flex#687]
Also on the OpenID Connect CLient form, can we add a Finish button to the client form in addition to Next. Maybe I don’t need to go through all the forms. A shortcut on all the pages to submit the client would be nice.

**Comment by nynymike** [comment]
This should probably be two distinct issues.

**Comment by mjatin-dev** [comment]
> This should probably be two distinct issues.

Create another issue Thanks

**Comment by mjatin-dev** [comment]
Fixed and merged
