### ISSUE TITLE
feat(portal-gateway): API for licenseSpring credentials

### ISSUE THREAD

**Issue by soheil-star01** [GluuFederation/flex#694]
-------------------

### Description

API key, shared key and product code should be hidden from the user (**as these are Gluu credentials**.). The user should be able to activate the license using license-key.

The [proposed solution](https://github.com/GluuFederation/flex/issues/497) : 
Every time before calling the licenseSpring APIs, Admin UI backend (config-API plugin) will call the following endpoints of Gluu's Internal Rest Application.
/licenseSpring/credentials (to get signed and encrypted API key, shared key, product code)
/licenseSpring/credentials/keys (to get keys to decrypt and verify credentials)
We will configure allowed hostnames in Gluu's Internal Rest Application. The requests from the configured hostnames will be only allowed to Gluu's Internal Rest Application

- Development target issue (https://github.com/GluuFederation/flex/issues/497)
  

-------------------

### Steps

- [ ] Make the Portal Gateway ready.
- [ ] Write the TDD.
- [ ] Test the API endpoints from Admin-ui

**Comment by duttarnab** [comment]
This is done.
