### ISSUE TITLE
fix(casa): cancel button not working

### ISSUE THREAD

**Issue by manojs1978** [GluuFederation/flex#768]
**Describe the bug**
cancel button not working in password reset

**To Reproduce**
1. launch casa
2. open passwd reset 
3. click on cancel button

**Expected behavior**
should able to cancel passwd reset.

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/219600053-7514e8c0-a595-41fa-ac95-561fbc50b58f.png)

**Desktop (please complete the following information):**
  - OS: ubuntu
  - Version 20
  -  DB openDJ

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jgomer2001** [comment]
@manojs1978  Can you elaborate on why it is not working? what's the expected behavior for you?

**Comment by manojs1978** [comment]
Hello @jgomer2001 ,
i was expecting when we click on cancel button, it will cancel passwd reset functionality  and retrun to home page.

**Comment by jgomer2001** [comment]
It has never worked that way.
