### ISSUE TITLE
fix(admin-ui): auth config properties page displays a white screen

### ISSUE THREAD

**Issue by moabu** [GluuFederation/flex#769]
![image](https://user-images.githubusercontent.com/47318409/220351068-0448ab84-27ad-40a5-bfaf-99b3121c887d.png)

Heading to `Auth Server` --> `Configuration` --> `Properties` results ina white screen in the admin ui . 

**Persistence used is mysql**

**Comment by duttarnab** [comment]
![image](https://user-images.githubusercontent.com/32794267/221342690-ddcc8236-3653-4baf-bf48-510356ec46a1.png)

**Comment by duttarnab** [comment]
fixed https://github.com/GluuFederation/flex/issues/848
