### ISSUE TITLE
fix(admin-ui): Problems getting API access token in order to process api calls

### ISSUE THREAD

**Issue by gustavovalverde** [GluuFederation/flex#785]
**Describe the bug**

**To Reproduce**
1. Install on GKE using this instructions: https://github.com/GluuFederation/flex/blob/main/docs/install/helm-install/google-gke.md
2. Configure the Helm chart with `adminUiEnabled: true`
3. Open `https://<domain>/admin`
4. See error: `The UI backend service is down` and developer tools shows `Problems getting API access token in order to process api calls.`

**Expected behavior**
No error

**Screenshots**
<img width="1088" alt="image" src="https://user-images.githubusercontent.com/16890942/220869157-7b754278-5d62-43f5-a3f6-97d4f60f8628.png">

**Additional context**
`config-api` deployment shows:
`ERROR jans.configapi.util.JwtUtil JwtUtil.java:53- Not jwt token undefined`

`auth-server` deployment shows:
```
ERROR [qtp1640899500-19] [io.jans.as.model.crypto.AuthCryptoProvider] (AuthCryptoProvider.java:404) - Uninitialized keystore
ERROR [qtp1640899500-19] [io.jans.as.model.crypto.AuthCryptoProvider] (AuthCryptoProvider.java:234) - Failed to find private key by kid: null, signatureAlgorithm: RS256(check whether web keys JSON in persistence corresponds to keystore file), keySelectionStrategy: OLDER
```

I once had this issue when using `CloudSpanner`. I've deployed with `MySQL` this time.
- https://github.com/GluuFederation/cloud-native-edition/issues/414

**Comment by gustavovalverde** [comment]
Pinging @duttarnab as I'm not sure if this is an upstream issue with `jans-config-api`

**Comment by gustavovalverde** [comment]
I can't see any secrets being mounted to the containers. This might be the reason why authentication is failing between services.

**Comment by moabu** [comment]
it seems like your auth keys are corrupted  . Try rotating your auth keys first

**Comment by gustavovalverde** [comment]
Found the issue. This is caused because a `helm uninstall gluu` does not delete all the resources deployed by the install. This is mainly as some jobs create secrets and configs which are not being managed by `helm`.

**Comment by moabu** [comment]
Yes this intended behavior. The main gluu secret and config map is not to be deleted as that causes catastrophic destruction.
