### ISSUE TITLE
Can't load all scopes

### ISSUE THREAD

**Issue by mzico** [GluuFederation/flex#790]
I have around 120 scopes in my server, can't load / use scopes more than 102 scopes. 

Here in attached recording, we can see that... there are 121 scopes all together. 
But when I am searching for all scopes, they are not loading. 

If I try to use those custom scopes which were created after 102th number, they are not loading as well. 

Here is the recording: https://youtu.be/0iBkiBeZCYg

**Comment by duttarnab** [comment]
As per current logic, the `redirect_uris` is mandatory for only `authorization_code` or `implicit` `grant_types`. If you leave the `grant_types` field blank then it will take the default value i.e. `authorization_code`. So` redirect_uri` is required if the `grant_types` field is blank but not mandatory if grant_type is other than authorization_code or implicit.

We will not mark the `redirect_uris field` with red Astrics but put an alert if the field is left blank with `grant_types` `authorization_code` and `implicit`.

**Comment by duttarnab** [comment]
Changes to be done : 

1.  We have `2` search records inputs on the scopes list page. We need to remove this search input (marked with red circle) from the pages where we have the search pattern box. 
![image](https://user-images.githubusercontent.com/32794267/223041058-6b837b12-becc-4689-aad4-98fd76a314f6.png)

2. On oidc client add/edit page the `scope` field should search scopes upon entering the pattern. Currently, it fetches only 100 scopes on loading the page and user is allowed to select from those 100 scopes (This is faulty).

**Comment by mzico** [comment]
@mjatin-dev @duttarnab : any update on this?

**Comment by duttarnab** [comment]
Issue fixed and verified.
