### ISSUE TITLE
feat(admin-ui): add page names Agama under Auth server

### ISSUE THREAD

**Issue by mjatin-dev** [GluuFederation/flex#806]
Need to add Agama page under Auth server as provided in the TUI
![thumb-Clipboard - March 2, 2023 10_30 PM](https://user-images.githubusercontent.com/32476704/222662013-892624bb-15de-4149-bce2-7c70b7f4cc1b.png)
Follow are the api's need to be used
![Clipboard - March 2, 2023 11_07 PM](https://user-images.githubusercontent.com/32476704/222662062-670543b5-8272-48e3-a547-d7f52b34707d.png)

**Comment by duttarnab** [comment]
done
