### ISSUE TITLE
feat(admin-ui): Mark mandatory fields in UI

### ISSUE THREAD

**Issue by mzico** [GluuFederation/flex#807]
Went to create a client and faced issue. I didn't have any indication what I am doing wrong. 
Here is the recorded screen: https://www.youtube.com/watch?v=HtU0CEocGV8&ab_channel=MohibZico

Turned out: "Redirect URI" is a mandatory field and after inserting a fake redirect uri, it worked.  

We need to mark all mandatory fields so user can understand properly.

**Comment by duttarnab** [comment]
As per current logic, the `redirect_uris` is mandatory for only `authorization_code` or `implicit` `grant_types`. If you leave the `grant_types` field blank then it will take the default value i.e. `authorization_code`. So` redirect_uri` is required if the `grant_types` field is blank but not mandatory if grant_type is other than authorization_code or implicit.

We will not mark the `redirect_uris field` with red Astrics but put an alert if the field is left blank with `grant_types` `authorization_code` and `implicit`.

**Comment by duttarnab** [comment]
done
