### ISSUE TITLE
fix(adminui) newly added scope is not showing 

### ISSUE THREAD

**Issue by manojs1978** [GluuFederation/flex#812]
**Describe the bug**
 newly added scope is not showing 

**To Reproduce**
1. install adminui
2. launch and navigate to scope
3. add new scope
4. search for newly created scope
5. See error

**Expected behavior**
should able to edit/delete/view newly created scope

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/223376243-712b4c50-1133-4b87-838b-bf62d3f775ac.png)

**Desktop (please complete the following information):**
  - OS:ubuntu
  - Version 20
  - DB mysql

**Smartphone (please complete the following information):**

**Additional context**

**Comment by duttarnab** [comment]
We have 2 search boxes on the page. The first search box only searches from the pattern listed on the page. We do not need this. @jv18creator could you remove `1` box from scopes list page

![image](https://user-images.githubusercontent.com/32794267/226285761-9e2086a9-c507-469a-bda5-909cd2afe802.png)

**Comment by jv18creator** [comment]
we can set the `search: false` on `MaterialTable` component in `ScopeListPage.js` file to remove the first search box.
