### ISSUE TITLE
bug(admin-ui): CASA authentication script has wrong script inside - CASA failing

### ISSUE THREAD

**Issue by mzico** [GluuFederation/flex#856]
`https://[flex_hostname]/casa` failing to perform it's operation properly because CASA script is wrong inside admin-ui. 

- Problematic scenario: 
  - In flex admin UI, I enabled three scripts…. SuperGluu, OTP and Fido2
  - In flex/casa admin, I tried to allow three methods system wise
  - So, ideally my newly created user ( mohib ) should log into CASA without any 2FA prompt ( as I haven’t selected any 2FA from this user “mohib” profile )
   - When I am logging into casa as user “mohib”; SUPERGLUU / FIDO2 SCRIPT WAS LOADING THOUGH I HAVEN'T SELECTED ANY SCRIPT FROM "mohib" PROFILE
- Workaround / Resolution: 
  - Log into admin-ui
  - Scripts > CASA > replace existing script with `https://github.com/GluuFederation/flex/blob/main/casa/extras/Casa.py`
  - Save
  - Test

**Comment by duttarnab** [comment]
@mzico @devrimyatar I could see the incorrect casa script in persistence after installation. So we need to check the installation script to find out why it is happening. 

![image](https://user-images.githubusercontent.com/32794267/225617926-2d15ecec-c249-4e61-bec7-1d79d106f583.png)

**Comment by maduvena** [comment]
[flex-setup.log](https://github.com/GluuFederation/flex/files/11049788/flex-setup.log)

Line 100 - 09:50:51 03/23/23 - the contents of the script are wrong. It should be casa script and not fido2

**Comment by jgomer2001** [comment]
i'm able to reproduce this too.
