### ISSUE TITLE
feat(admin-ui): user should be able to submit SSA from admin-ui

### ISSUE THREAD

**Issue by duttarnab** [GluuFederation/flex#874]
- [x] user should be able to submit SSA from admin-ui (not set-up script).
- [x] user should be able to re-submit SSA details using admin-ui if previously entered SSA is not valid.

**Comment by moabu** [comment]
To clarify the user still needs to pass the SSA during setup as a way of enforcing it. 

Here are the points: 

A. The user provides it during setup as is.
B. If for any reason the client gets removed, expired…etc the customer can use their valid SSA in which the admin ui will prompt for to register again.
C. If the SSA is invalidated and the client expires or gets removed the customer would be prompted for the SSA in which they have to contact support to renew at the moment  and get a new one without invalidating their current admin ui setup. In the future the user would just log into Agama lab and reissue a new one themselves.

**Comment by duttarnab** [comment]
Hi @nynymike 




> C. If the becomes invalid, the AdminUI should try to re-register a new client using the old SSA. If for some reason client registration fails, the AdminUI should prompt for a new SSA. Updating the client that calls the License API should not invalidate the current admin ui setup.

It means we will need to save the last SSA in admin-ui configuration (persistence).

**Comment by duttarnab** [comment]
**Steps**:

1. Call `GET` `/admin-ui/license/isConfigValid` 

**Response**
- {apiResult: true, responseCode: 200, responseMessage: "No error in license configuration."}
   Remarks: Go to **step 3**

-  {apiResult: false, ...}
    Remarks: If `apiResult` is `false` then go to **step 2**

2. Show the page to upload `ssa.jwt` file. On click of `Submit` button it will call `POST` `/admin-ui/license/ssa`

**Response**
- {apiResult: true, responseCode: 201, responseMessage: "SSA saved successfully."}
   Remarks: Go to **step 3**

- {apiResult: false, ...}
  Remarks: Show the error page with following 

```
Error in processing SSA. It may due to any of the following reason:
1. Invalid SSA. Please contact Gluu's team to verify if SSA is correct.
Please contact the site administrator or check server logs.
```

3. `GET` `/admin-ui/license/isActive` (already implemented)

**Comment by duttarnab** [comment]
Done
