### ISSUE TITLE
feat (admin-ui): add feature to show error on custom scripts 

### ISSUE THREAD

**Issue by duttarnab** [GluuFederation/flex#882]
![Clipboard - March 24, 2023 2_31 PM](https://user-images.githubusercontent.com/32794267/227493082-35d24159-ba11-4617-b9d1-e74136131b01.png)

**Comment by jv18creator** [comment]
add validation for the script `name` field before saving the script.
rule: Name should contain only letters, digits and underscores. **NO SPACES**

**Comment by duttarnab** [comment]
Done
