### ISSUE TITLE
feat (flex-linux-setup): remove credentialsEncryptionKey field from admin-ui configuration

### ISSUE THREAD

**Issue by duttarnab** [GluuFederation/flex#921]
Parent ticket# https://github.com/JanssenProject/jans/issues/4539

Please remove `credentialsEncryptionKey` from `licenseConfig` (`jansConfApp` field in admin-ui).

![image](https://user-images.githubusercontent.com/32794267/230916564-1ba187d9-36f2-4b59-921b-f619d882abbc.png)

**Comment by devrimyatar** [comment]
Question: Should I also remove key creation?
