### ISSUE TITLE
feat(flex-linux-setup): the installation script should use node version `18.16.0` for flex installtion

### ISSUE THREAD

**Issue by duttarnab** [GluuFederation/flex#948]
Admin UI has been refactored to use :
**node** version `18.16.0`
**npm** version `9.x`

We need the flex installation script to install the node and npm of the above version to test Admin UI

**Comment by duttarnab** [comment]
Hi @devrimyatar 

The changes done is working on ubuntu 20.04 but not working on unbntu 22.04.

Getting the following error while building admin-ui using node-18.16.0 (https://nodejs.org/dist/v18.16.0/node-v18.16.0-linux-x64.tar.xz) unbntu 22.04.

**Comment by iromli** [comment]
@duttarnab as per 96d82038fe752cfff4e722113c757978b2b39119, the installed NodeJS and NPM have been upgraded to `18.16.x` and `9x` respectively.

**Comment by duttarnab** [comment]
Done
