### ISSUE TITLE
fix (admin-ui): bugs in admin-ui `prod` built with node version `18.x`

### ISSUE THREAD

**Issue by duttarnab** [GluuFederation/flex#952]
**Bugs:**

- [ ] Gluu image not loading.

![image](https://user-images.githubusercontent.com/32794267/233783287-20d66f40-ff60-46dc-ac01-53d4ad0418e5.png)

![image](https://user-images.githubusercontent.com/32794267/233783399-752b307a-91d8-432a-9b7a-8e513e70c160.png)

- [ ] MAU graph layout is not visible

![image](https://user-images.githubusercontent.com/32794267/233783993-6ccdd127-2d8d-4f74-a422-9a47c9cec180.png)

**Comment by jv18creator** [comment]
Bugs are fixed.
