### ISSUE TITLE
docs(license): create documentation page for generating Flex licenses

### ISSUE THREAD

**Issue by shmorri** [GluuFederation/flex#986]
The process to generate and manage licenses for Gluu Flex is not currently documented, but is incredibly important. We need a page for license management. This includes the SSA and the Admin UI licenses.

The best location for this document is in the administration section, perhaps https://docs.gluu.org/v5.0.0-12/admin/license/

**Comment by duttarnab** [comment]
Covered as part of `https://github.com/GluuFederation/flex/issues/1063`
