### ISSUE TITLE
test (admin-ui): check the working of existing test cases in admin-ui

### ISSUE THREAD

**Issue by duttarnab** [GluuFederation/flex#987]
Check if below test cases in admin ui working properly.
**Admin**
- [ ] Custom scripts
- [ ] Role 
**Auth Server**
- [ ] Client
- [ ] Configuration --> Defaults
- [ ] Configuration --> Keys
- [ ] Configuration  --> Properties
- [ ] Scopes
**Schema**
- [ ] Person

**Comment by jv18creator** [comment]
PR Changes include

- `react-tooltip` migration from v4 to v5
- added `@testing-library/user-event` to test user interaction events such as mouse over
- created `jest.config` to configure and run the tests

**Comment by duttarnab** [comment]
Done
