### ISSUE TITLE
fix (admin-ui): SMTP test failed when configuration is not saved.

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [GluuFederation/flex#996]
**Describe the bug**

SMTP test failed when configuration is not saved.

**To Reproduce**
1. Install Flex
2. Go to Admin UI
3. Go to SMTP.
4. Set SMTPconfiguration.
5. Test SMTP configuration 

**Expected behavior**
SMTP config test must be successful without saving properties.

**Actual behavior**

SMTP config properties need to be saved before testing the config .

**Screenshots**
![Screenshot (42)](https://user-images.githubusercontent.com/34593983/236414151-c314dd84-e166-48ce-9bd0-28b5906c24c8.png)
when SMTP properties are not saved then SMTP config test  failed

![Screenshot (46)](https://user-images.githubusercontent.com/34593983/236414322-1e775243-b835-403d-b4be-e4cfd9d9357e.png)
when SMTP properties are  saved then  SMTP config test  passed.

**Desktop (please complete the following information):**
  - OS:  ubuntu 22
  - Browser chrome
  - Version  flex latest.

**Comment by duttarnab** [comment]
Fixed
